### ISSUE TITLE
Plugin powershell-v2 reported failure: Schema Missing

### ISSUE THREAD

**Issue by dicolanl** [Azure/autorest.powershell#1000]
How does one determine where this is failing?  the swagger seems fine, i checked it in VSCode with swagger add in and editor.swagger.io.  Neither report errors.

/root/.autorest/@autorest_powershell@3.0.494/node_modules/@autorest/powershell/dist/plugins/powershell-v2.js - FAILURE  {} Error: SCHEMA MISSING?
    at SchemaDefinitionResolver.resolveTypeDeclaration (/root/.autorest/@autorest_powershell@3.0.494/node_modules/@autorest/powershell/llcsharp/schema/schema-resolver.ts:40:13)
    at SchemaDefinitionResolver.resolveTypeDeclaration (/root/.autorest/@autorest_powershell@3.0.494/node_modules/@autorest/powershell/llcsharp/schema/schema-resolver.ts:121:21)
    at new ModelExtensionsNamespace (/root/.autorest/@autorest_powershell@3.0.494/node_modules/@autorest/powershell/models/model-extensions.ts:56:34)
    at Project.init (/root/.autorest/@autorest_powershell@3.0.494/node_modules/@autorest/powershell/internal/project.ts:269:29)
    at powershellV2 (/root/.autorest/@autorest_powershell@3.0.494/node_modules/@autorest/powershell/plugins/powershell-v2.ts:53:21)
    at /root/.autorest/@autorest_powershell@3.0.494/node_modules/@azure-tools/autorest-extension-base/extension-base.ts:68:9
PLUGIN FAILURE: SCHEMA MISSING?, Error: SCHEMA MISSING?
    at SchemaDefinitionResolver.resolveTypeDeclaration (/root/.autorest/@autorest_powershell@3.0.494/node_modules/@autorest/powershell/llcsharp/schema/schema-resolver.ts:40:13)
    at SchemaDefinitionResolver.resolveTypeDeclaration (/root/.autorest/@autorest_powershell@3.0.494/node_modules/@autorest/powershell/llcsharp/schema/schema-resolver.ts:121:21)
    at new ModelExtensionsNamespace (/root/.autorest/@autorest_powershell@3.0.494/node_modules/@autorest/powershell/models/model-extensions.ts:56:34)
    at Project.init (/root/.autorest/@autorest_powershell@3.0.494/node_modules/@autorest/powershell/internal/project.ts:269:29)
    at powershellV2 (/root/.autorest/@autorest_powershell@3.0.494/node_modules/@autorest/powershell/plugins/powershell-v2.ts:53:21)
    at /root/.autorest/@autorest_powershell@3.0.494/node_modules/@azure-tools/autorest-extension-base/extension-base.ts:68:9, {}
fatal   | Error: SCHEMA MISSING?
fatal   | Process() cancelled due to exception : Plugin powershell-v2 reported failure. / Error: Plugin powershell-v2 reported failure.
    at /root/.autorest/@autorestcore@3.9.2/node_modules/@autorest/core/dist/src_lib_autorest-corets.js:2817:19
    at ScheduleNode (/root/.autorest/@autorestcore@3.9.2/node_modules/@autorest/core/dist/src_lib_autorest-corets.js:1351:29)
error   |   Error: Plugin powershell-v2 reported failure.
error   | Autorest completed with an error. If you think the error message is unclear, or is a bug, please declare an issues at https://github.com/Azure/autorest/issues with the error message you are seeing.

**Comment by dolauli** [comment]
Please provide the detailed steps how to reproduce the issue including the swagger file.

**Comment by dicolanl** [comment]
@dolauli could you share an email?  its in private api file.

**Comment by dicolanl** [comment]
Found the problem.  there was multiple hosts in the file.  Removing to 1 host solved this.
