### ISSUE TITLE
A compilation error occurs when something in swagger is as follows

### ISSUE THREAD

**Issue by lijinpei2008** [Azure/autorest.powershell#1029]
**Before filling a bug**

- [x] have you checked the [faq](https://github.com/Azure/autorest/tree/main/docs/faq.md) for known issues.
- [x] have you checked existing issues

**Describe the bug**
A compilation error occurs when something in swagger is as follows:

https://github.com/Azure/azure-rest-api-specs-pr/blob/RPSaaSMaster/specification/mobilenetwork/resource-manager/Microsoft.MobileNetwork/stable/2022-11-01/ts29571.json#L308-L312

https://github.com/Azure/azure-rest-api-specs-pr/blob/RPSaaSMaster/specification/mobilenetwork/resource-manager/Microsoft.MobileNetwork/stable/2022-11-01/ts29571.json#L283-L287

**Expected behavior**

**Additional context**

**Log**
```
PS D:\_Code\3\azure-powershell\src\MobileNetwork> autorest --debug
AutoRest code generation utility [cli version: 3.6.2; node: v14.17.4]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
debug   | [0.85 s] Network Enabled: true
debug   | [0.92 s] The most recent installed version is 3.9.3
debug   | [0.92 s] requesting current version '3.9.3'
debug   | [0.92 s] Starting @autorest/core from C:\Users\v-jinpel\.autorest\@autorestcore@3.9.3\nodemodules\@autorest\core
info    |    Loading AutoRest core      'C:\Users\v-jinpel\.autorest\@autorestcore@3.9.3\nodemodules\@autorest\core\dist' (3.9.3)
verbose | [0.76 s]    Initial configuration file 'file:///D:/_Code/3/azure-powershell/src/MobileNetwork/README.md'
verbose | [0.76 s]    Including configuration file 'file:///D:/_Code/3/azure-powershell/src/MobileNetwork/README.md'
verbose | [0.78 s]    Including configuration file 'file:///D:/_Code/3/azure-powershell/src/readme.azure.noprofile.md'
verbose | [0.79 s]    Including configuration file 'file:///C:/Users/v-jinpel/.autorest/@autorestcore@3.9.3/nodemodules/@autorest/core/dist/resources/default-configuration.md'
verbose | [0.80 s]    Including configuration file 'file:///C:/Users/v-jinpel/.autorest/@autorestcore@3.9.3/nodemodules/@autorest/core/dist/resources/inspect.md'
verbose | [0.82 s]    Including configuration file 'file:///C:/Users/v-jinpel/.autorest/@autorestcore@3.9.3/nodemodules/@autorest/core/dist/resources/directives.md'
verbose | [0.83 s]    Including configuration file 'file:///C:/Users/v-jinpel/.autorest/@autorestcore@3.9.3/nodemodules/@autorest/core/dist/resources/pipeline.md'
verbose | [0.85 s]    Including configuration file 'file:///C:/Users/v-jinpel/.autorest/@autorestcore@3.9.3/nodemodules/@autorest/core/dist/resources/loader-openapi.md'
verbose | [0.87 s]    Including configuration file 'file:///C:/Users/v-jinpel/.autorest/@autorestcore@3.9.3/nodemodules/@autorest/core/dist/resources/miscellaneous.md'
verbose | [0.89 s]    Including configuration file 'file:///C:/Users/v-jinpel/.autorest/@autorestcore@3.9.3/nodemodules/@autorest/core/dist/resources/plugin-powershell.md'
verbose | [0.91 s]    Including configuration file 'file:///C:/Users/v-jinpel/.autorest/@autorestcore@3.9.3/nodemodules/@autorest/core/dist/resources/plugin-azureresourceschema.md'
verbose | [0.92 s]    Including configuration file 'file:///C:/Users/v-jinpel/.autorest/@autorestcore@3.9.3/nodemodules/@autorest/core/dist/resources/plugin-csharp.md'
verbose | [0.94 s]    Including configuration file 'file:///C:/Users/v-jinpel/.autorest/@autorestcore@3.9.3/nodemodules/@autorest/core/dist/resources/plugin-go.md'
verbose | [0.96 s]    Including configuration file 'file:///C:/Users/v-jinpel/.autorest/@autorestcore@3.9.3/nodemodules/@autorest/core/dist/resources/plugin-java.md'
verbose | [0.97 s]    Including configuration file 'file:///C:/Users/v-jinpel/.autorest/@autorestcore@3.9.3/nodemodules/@autorest/core/dist/resources/plugin-nodejs.md'
verbose | [0.99 s]    Including configuration file 'file:///C:/Users/v-jinpel/.autorest/@autorestcore@3.9.3/nodemodules/@autorest/core/dist/resources/plugin-php.md'
verbose | [1.01 s]    Including configuration file 'file:///C:/Users/v-jinpel/.autorest/@autorestcore@3.9.3/nodemodules/@autorest/core/dist/resources/plugin-python.md'
verbose | [1.02 s]    Including configuration file 'file:///C:/Users/v-jinpel/.autorest/@autorestcore@3.9.3/nodemodules/@autorest/core/dist/resources/plugin-ruby.md'
verbose | [1.04 s]    Including configuration file 'file:///C:/Users/v-jinpel/.autorest/@autorestcore@3.9.3/nodemodules/@autorest/core/dist/resources/plugin-typescript.md'
verbose | [1.06 s]    Including configuration file 'file:///C:/Users/v-jinpel/.autorest/@autorestcore@3.9.3/nodemodules/@autorest/core/dist/resources/plugin-validators.md'
verbose | [1.08 s]    Including configuration file 'file:///C:/Users/v-jinpel/.autorest/@autorestcore@3.9.3/nodemodules/@autorest/core/dist/resources/plugin-az.md'
verbose | [1.10 s]    Including configuration file 'file:///C:/Users/v-jinpel/.autorest/@autorestcore@3.9.3/nodemodules/@autorest/core/dist/resources/plugin-terraform.md'
verbose | [1.12 s]    Including configuration file 'file:///C:/Users/v-jinpel/.autorest/@autorestcore@3.9.3/nodemodules/@autorest/core/dist/resources/plugin-azure-functions.md'
verbose | [1.15 s]    Including configuration file 'file:///C:/Users/v-jinpel/.autorest/@autorestcore@3.9.3/nodemodules/@autorest/core/dist/resources/graphs.md'
verbose | [1.17 s]    Including configuration file 'file:///C:/Users/v-jinpel/.autorest/@autorestcore@3.9.3/nodemodules/@autorest/core/dist/resources/help-configuration.md'
info    |
The default version of @autorest/powershell has been bumped from 2.1+ to 3.0+.
 > If you still want to use 2.1+ version, please specify it with --use:@autorest/powershell@2.1.{x}, e.g 2.1.401.

info    |    Loading AutoRest extension '@autorest/powershell' (~3.0.0->3.0.497)
verbose | [1.27 s]    Including extension configuration file 'file:///C:/Users/v-jinpel/.autorest/@autorestpowershell@3.0.497/nodemodules/@autorest/powershell/readme.md'
verbose | [1.27 s]    Including configuration file 'file:///C:/Users/v-jinpel/.autorest/@autorestpowershell@3.0.497/nodemodules/@autorest/powershell/readme.md'
verbose | [1.29 s]    Including configuration file 'file:///C:/Users/v-jinpel/.autorest/@autorestpowershell@3.0.497/nodemodules/@autorest/powershell/autorest-configuration.md'
info    |    Loading AutoRest extension '@autorest/modelerfour' (4.15.414->4.15.414)
verbose | [1.43 s]    Including extension configuration file 'file:///C:/Users/v-jinpel/.autorest/@autorestmodelerfour@4.15.414/nodemodules/@autorest/modelerfour/readme.md'
verbose | [1.43 s]    Including configuration file 'file:///C:/Users/v-jinpel/.autorest/@autorestmodelerfour@4.15.414/nodemodules/@autorest/modelerfour/readme.md'
debug   | [2.51 s] swagger-document/loader-swagger - START inputs = 0
debug   | [2.51 s] openapi-document/loader-openapi - START inputs = 0
debug   | [2.51 s] pipeline-emitter - START inputs = 0
debug   | [2.51 s] configuration-emitter - START inputs = 0
debug   | [2.51 s] pipeline-emitter - END [0.07 s][87 MB]
debug   | [2.51 s] configuration-emitter - END [0.08 s][87 MB]
verbose | [2.52 s] Reading OpenAPI 2.0 file file:///D:/_Code/azure-rest-api-specs-pr/specification/mobilenetwork/resource-manager/Microsoft.MobileNetwork/preview/2022-04-01-preview/ts29571.json
debug   | [2.53 s] openapi-document/loader-openapi - END [0.08 s][88 MB]
debug   | [2.53 s] swagger-document/loader-swagger - END [0.09 s][88 MB]
debug   | [2.53 s] openapi-document/individual/transform - SKIPPING
debug   | [2.53 s] openapi-document/individual/schema-validator-openapi - SKIPPING
debug   | [2.53 s] openapi-document/individual/full-ref-resolver - SKIPPING
debug   | [2.53 s] openapi-document/individual/identity - SKIPPING
debug   | [2.53 s] swagger-document/individual/transform - START inputs = 1
debug   | [2.53 s] swagger-document/individual/transform - END [0 s][88 MB]
debug   | [2.53 s] swagger-document/individual/schema-validator-swagger - START inputs = 1
debug   | [2.77 s] swagger-document/individual/schema-validator-swagger - END [0.24 s][87 MB]
debug   | [2.77 s] swagger-document/individual/full-ref-resolver - START inputs = 1
debug   | [2.77 s] swagger-document/individual/full-ref-resolver - END [0 s][87 MB]
debug   | [2.77 s] swagger-document/identity - START inputs = 1
debug   | [2.77 s] swagger-document/individual/identity - START inputs = 1
debug   | [2.77 s] swagger-document/identity - END [0 s][87 MB]
debug   | [2.77 s] swagger-document/individual/identity - END [0 s][87 MB]
debug   | [2.77 s] openapi-document/openapi-document-converter - START inputs = 1
debug   | [2.78 s] openapi-document/openapi-document-converter - END [0 s][89 MB]
debug   | [2.78 s] openapi-document/transform - START inputs = 1
debug   | [2.78 s] openapi-document/transform - END [0 s][89 MB]
debug   | [2.78 s] openapi-document/semantic-validator - START inputs = 1
debug   | [2.78 s] openapi-document/semantic-validator - END [0 s][89 MB]
debug   | [2.78 s] openapi-document/allof-cleaner - START inputs = 1
debug   | [2.79 s] openapi-document/allof-cleaner - END [0 s][89 MB]
debug   | [2.79 s] openapi-document/tree-shaker - START inputs = 1
debug   | [2.79 s] openapi-document/tree-shaker - END [0 s][91 MB]
debug   | [2.79 s] openapi-document/multi-api-merger - START inputs = 1
debug   | [2.81 s] openapi-document/multi-api-merger - END [0.01 s][94 MB]
debug   | [2.81 s] openapi-document/components-cleaner - START inputs = 1
debug   | [2.82 s] openapi-document/components-cleaner - END [0.01 s][96 MB]
debug   | [2.82 s] openapi-document/component-modifiers - START inputs = 1
debug   | [2.82 s] openapi-document/component-modifiers - END [0 s][97 MB]
debug   | [2.82 s] openapi-document/api-version-parameter-handler - START inputs = 1
debug   | [2.82 s] openapi-document/api-version-parameter-handler - END [0 s][97 MB]
debug   | [2.82 s] openapi-document/profile-filter - START inputs = 1
debug   | [2.82 s] openapi-document/profile-filter - END [0 s][97 MB]
debug   | [2.82 s] openapi-document/model-deduplicator - START inputs = 1
debug   | [2.82 s] openapi-document/emitter - START inputs = 1
debug   | [2.82 s] openapi-document/model-deduplicator - END [0 s][97 MB]
debug   | [2.82 s] openapi-document/emitter - END [0 s][97 MB]
debug   | [2.82 s] openapi-document/enum-deduplicator - START inputs = 1
debug   | [2.85 s] openapi-document/enum-deduplicator - END [0.02 s][88 MB]
debug   | [2.85 s] openapi-document/subset-reducer - START inputs = 1
debug   | [2.85 s] openapi-document/subset-reducer - END [0 s][88 MB]
debug   | [2.85 s] openapi-document/multi-api/reset-identity - START inputs = 1
debug   | [2.85 s] openapi-document/multi-api/reset-identity - END [0 s][88 MB]
debug   | [2.85 s] openapi-document/multi-api/identity - START inputs = 1
debug   | [2.85 s] openapi-document/multi-api/identity - END [0 s][88 MB]
debug   | [2.85 s] openapi-document/multi-api/emitter - START inputs = 1
debug   | [2.85 s] prechecker - START inputs = 1
debug   | [2.85 s] openapi-document/multi-api/emitter - END [0 s][89 MB]
warning | PreCheck/CheckDuplicateSchemas | Checking for duplicate schemas, this could take a (long) while.  Run with --verbose for more detail.
C:\Users\v-jinpel\.autorest\@autorest_modelerfour@4.15.414\node_modules\@autorest\modelerfour\dist\quality-precheck\prechecker.js - FAILURE  {} Error: Circular $ref in Model -- #/components/schemas/schemas:28 :: ["#/components/schemas/schemas:28"]
    at dereference (/node_modules/@azure-tools/openapi/dist/common.js:48:19)
    at Object.dereference (/node_modules/@azure-tools/openapi/dist/common.js:60:20)
    at QualityPreChecker.resolve (C:\Users\v-jinpel\.autorest\@autorest_modelerfour@4.15.414\node_modules\@autorest\modelerfour\dist\quality-precheck\prechecker.js:46:26)
    at innerCheckForDuplicateSchemas (C:\Users\v-jinpel\.autorest\@autorest_modelerfour@4.15.414\node_modules\@autorest\modelerfour\dist\quality-precheck\prechecker.js:173:60)
    at QualityPreChecker.checkForDuplicateSchemas (C:\Users\v-jinpel\.autorest\@autorest_modelerfour@4.15.414\node_modules\@autorest\modelerfour\dist\quality-precheck\prechecker.js:219:18)
    at QualityPreChecker.process (C:\Users\v-jinpel\.autorest\@autorest_modelerfour@4.15.414\node_modules\@autorest\modelerfour\dist\quality-precheck\prechecker.js:332:14)
    at processRequest (C:\Users\v-jinpel\.autorest\@autorest_modelerfour@4.15.414\node_modules\@autorest\modelerfour\dist\quality-precheck\prechecker.js:17:31)
    at async /node_modules/@azure-tools/autorest-extension-base/dist/extension-base.js:42:17
PLUGIN FAILURE: Circular $ref in Model -- #/components/schemas/schemas:28 :: ["#/components/schemas/schemas:28"], Error: Circular $ref in Model -- #/components/schemas/schemas:28 :: ["#/components/schemas/schemas:28"]
    at dereference (/node_modules/@azure-tools/openapi/dist/common.js:48:19)
    at Object.dereference (/node_modules/@azure-tools/openapi/dist/common.js:60:20)
    at QualityPreChecker.resolve (C:\Users\v-jinpel\.autorest\@autorest_modelerfour@4.15.414\node_modules\@autorest\modelerfour\dist\quality-precheck\prechecker.js:46:26)
    at innerCheckForDuplicateSchemas (C:\Users\v-jinpel\.autorest\@autorest_modelerfour@4.15.414\node_modules\@autorest\modelerfour\dist\quality-precheck\prechecker.js:173:60)
    at QualityPreChecker.checkForDuplicateSchemas (C:\Users\v-jinpel\.autorest\@autorest_modelerfour@4.15.414\node_modules\@autorest\modelerfour\dist\quality-precheck\prechecker.js:219:18)
    at QualityPreChecker.process (C:\Users\v-jinpel\.autorest\@autorest_modelerfour@4.15.414\node_modules\@autorest\modelerfour\dist\quality-precheck\prechecker.js:332:14)
    at processRequest (C:\Users\v-jinpel\.autorest\@autorest_modelerfour@4.15.414\node_modules\@autorest\modelerfour\dist\quality-precheck\prechecker.js:17:31)
    at async /node_modules/@azure-tools/autorest-extension-base/dist/extension-base.js:42:17, {}
fatal   | Error: Circular $ref in Model -- #/components/schemas/schemas:28 :: ["#/components/schemas/schemas:28"]
fatal   | Process() cancelled due to exception : Plugin prechecker reported failure. / Error: Plugin prechecker reported failure.
    at C:\Users\v-jinpel\.autorest\@autorestcore@3.9.3\node_modules\@autorest\core\dist\src_lib_autorest-corets.js:2817:19
    at ScheduleNode (C:\Users\v-jinpel\.autorest\@autorestcore@3.9.3\node_modules\@autorest\core\dist\src_lib_autorest-corets.js:1351:29)
error   |   Error: Plugin prechecker reported failure.
error   | Autorest completed with an error. If you think the error message is unclear, or is a bug, please declare an issues at https://github.com/Azure/autorest/issues with the error message you are seeing.
debug   | [2.88 s] Shutting Down.
debug   | [2.88 s] Exiting.
```

**Comment by timotheeguerin** [comment]
Transfering to autorest.powershell repo. You have modelerfourpinned to a 2 years old version with many bugs. Please update
