### ISSUE TITLE
build-module.ps1 - The parameter 'Body' has multiple parameter types

### ISSUE THREAD

**Issue by Thom-Ernst** [Azure/autorest.powershell#1304]
Environment:
Powershell 7.4.1
Node v18.18.2
@autorestcore@3.9.4
@autorest/powershell' (~3.0.0->3.0.415)
'@autorest/modelerfour' (4.15.414->4.15.414)

I am trying to build the module as per documentation but get the following message:
```
PS C:\Users\username\swaggerautogen\generated> .\build-module.ps1
Creating isolated process...
Cleaning build folders...
Compiling module...
Creating exports and docs...
$ParsingMetadataException/   at Sample.API.Runtime.PowerShell.ParameterGroup..ctor(String parameterName, Parameter[] parameters, String[] allVariantNames) in C:\Users\username\swaggerautogen\generated\generated\runtime\BuildTime\Models\PsProxyTypes.cs:line 201
   at Sample.API.Runtime.PowerShell.PsProxyTypeExtensions.<>c__DisplayClass7_0.<ToParameterGroups>b__3(IGrouping`2 pg) in C:\Users\username\swaggerautogen\generated\generated\runtime\BuildTime\Models\PsProxyTypes.cs:line 487
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.ToArray()
   at Sample.API.Runtime.PowerShell.VariantGroup..ctor(String moduleName, String cmdletName, Variant[] variants, String outputFolder, String profileName, Boolean isTest, Boolean isInternal) in C:\Users\username\swaggerautogen\generated\generated\runtime\BuildTime\Models\PsProxyTypes.cs:line 66
   at Sample.API.Runtime.PowerShell.ExportProxyCmdlet.<>c__DisplayClass36_2.<ProcessRecord>b__10(IGrouping`2 vg) in C:\Users\username\swaggerautogen\generated\generated\runtime\BuildTime\Cmdlets\ExportProxyCmdlet.cs:line 68
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.SparseArrayBuilder`1.ReserveOrAdd(IEnumerable`1 items)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray()
   at Sample.API.Runtime.PowerShell.ExportProxyCmdlet.ProcessRecord() in C:\Users\username\swaggerautogen\generated\generated\runtime\BuildTime\Cmdlets\ExportProxyCmdlet.cs:line 66
Export-ProxyCmdlet: C:\Users\username\swaggerautogen\generated\build-module.ps1:134
Line |
 134 |    Export-ProxyCmdlet -ModuleName $moduleName -ModulePath $modulePaths …
     |    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The parameter 'Body' has multiple parameter types [IApicontroller1ApplicationClusterPackage[], IApicontroller1BackupPolicy[],
     | IApicontroller1BladeEnclosure[]] defined, which is not supported.
```
This after running the command ` autorest --powershell --input-file:'.\swaggerfile.json'`

This is my swaggerfile
```
{
  "openapi": "3.0.1",
  "servers": [
    {
      "url": "http://apiurl.com"
    }
  ],
  "info": {
    "title": "Import API",
    "version": "v1"
  },
  "paths": {
    "/api/import/controller1/ApplicationClusterPackage": {
      "post": {
        "tags": [
          "controller1"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/Apicontroller1ApplicationClusterPackage"
                }
              }
            },
            "text/json": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/Apicontroller1ApplicationClusterPackage"
                }
              }
            },
            "application/*+json": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/Apicontroller1ApplicationClusterPackage"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/import/controller1/BackupPolicy": {
      "post": {
        "tags": [
          "controller1"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/Apicontroller1BackupPolicy"
                }
              }
            },
            "text/json": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/Apicontroller1BackupPolicy"
                }
              }
            },
            "application/*+json": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/Apicontroller1BackupPolicy"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    },
    "/api/import/controller1/BladeEnclosure": {
      "post": {
        "tags": [
          "controller1"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/Apicontroller1BladeEnclosure"
                }
              }
            },
            "text/json": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/Apicontroller1BladeEnclosure"
                }
              }
            },
            "application/*+json": {
              "schema": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/Apicontroller1BladeEnclosure"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Apicontroller1ApplicationClusterPackage": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32"
          },
          "name": {
            "type": "string",
            "nullable": true
          },
          "code": {
            "type": "string",
            "nullable": true
          },
          "description": {
            "type": "string",
            "nullable": true
          },
          "startDate": {
            "type": "string",
            "format": "date-time",
            "nullable": true
          },
          "endDate": {
            "type": "string",
            "format": "date-time",
            "nullable": true
          },
          "status": {
            "type": "string",
            "nullable": true
          },
          "owner": {
            "type": "string",
            "nullable": true
          },
          "preferredNode": {
            "type": "string",
            "nullable": true
          },
          "applicationImpact": {
            "type": "integer",
            "format": "int32"
          },
          "supplier": {
            "type": "string",
            "nullable": true
          },
          "bil": {
            "type": "string",
            "nullable": true
          },
          "supportHours": {
            "type": "string",
            "nullable": true
          },
          "externalreference": {
            "type": "string",
            "nullable": true
          },
          "importStatus": {
            "type": "string",
            "nullable": true
          },
          "globalSession": {
            "type": "string",
            "nullable": true
          },
          "rfsReference": {
            "type": "string",
            "nullable": true
          },
          "logTime": {
            "type": "string",
            "format": "date-time"
          }
        },
        "additionalProperties": false
      },
      "Apicontroller1BackupPolicy": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "description": "Auto generated : do not fill out",
            "format": "int32"
          },
          "name": {
            "type": "string",
            "nullable": true
          },
          "code": {
            "type": "string",
            "nullable": true
          },
          "description": {
            "type": "string",
            "nullable": true
          },
          "startDate": {
            "type": "string",
            "format": "date-time",
            "nullable": true
          },
          "endDate": {
            "type": "string",
            "format": "date-time",
            "nullable": true
          },
          "status": {
            "type": "string",
            "description": "values (in production,archived)",
            "nullable": true
          },
          "owner": {
            "type": "string",
            "nullable": true
          },
          "applicationImpact": {
            "type": "integer",
            "format": "int32"
          },
          "backupPolicyType": {
            "type": "string",
            "nullable": true
          },
          "retention": {
            "type": "string",
            "nullable": true
          },
          "externalreference": {
            "type": "string",
            "description": "3th part CI unique identifier",
            "nullable": true
          },
          "importStatus": {
            "type": "string",
            "nullable": true
          },
          "globalSession": {
            "type": "string",
            "description": "Unique identifier for the calling session",
            "nullable": true
          },
          "rfsReference": {
            "type": "string",
            "nullable": true
          },
          "logTime": {
            "type": "string",
            "description": "Auto generated : do not fill out",
            "format": "date-time"
          }
        },
        "additionalProperties": false
      },
      "Apicontroller1BladeEnclosure": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int32"
          },
          "name": {
            "type": "string",
            "nullable": true
          },
          "code": {
            "type": "string",
            "nullable": true
          },
          "description": {
            "type": "string",
            "nullable": true
          },
          "startDate": {
            "type": "string",
            "format": "date-time",
            "nullable": true
          },
          "endDate": {
            "type": "string",
            "format": "date-time",
            "nullable": true
          },
          "status": {
            "type": "string",
            "description": "Values (In Production,In Repair/Maintenance,Ordered,Out of Production,\r\nPre-Production,\r\nRemoved,\r\nReserved,\r\nScrapped)",
            "nullable": true
          },
          "owner": {
            "type": "string",
            "nullable": true
          },
          "applicationImpact": {
            "type": "integer",
            "format": "int32"
          },
          "endOfSupport": {
            "type": "string",
            "format": "date-time",
            "nullable": true
          },
          "model": {
            "type": "string",
            "nullable": true
          },
          "productNumber": {
            "type": "string",
            "nullable": true
          },
          "serialNumber": {
            "type": "string",
            "nullable": true
          },
          "supplier": {
            "type": "string",
            "nullable": true
          },
          "primaryIpaddress": {
            "type": "string",
            "nullable": true
          },
          "bil": {
            "type": "string",
            "nullable": true
          },
          "supportHours": {
            "type": "string",
            "nullable": true
          },
          "externalreference": {
            "type": "string",
            "nullable": true
          },
          "importStatus": {
            "type": "string",
            "nullable": true
          },
          "globalSession": {
            "type": "string",
            "nullable": true
          },
          "rfsReference": {
            "type": "string",
            "nullable": true
          },
          "logTime": {
            "type": "string",
            "format": "date-time"
          }
        },
        "additionalProperties": false
      }
    }
  }
}
```

**Comment by dolauli** [comment]
Generator group APIs based on the `operationId`. Please add operationId for each of your API in swagger.
```
{
    "openapi": "3.0.1",
    "servers": [
      {
        "url": "http://apiurl.com"
      }
    ],
    "info": {
      "title": "Import API",
      "version": "v1"
    },
    "paths": {
      "/api/import/controller1/ApplicationClusterPackage": {
        "post": {
          "tags": [
            "controller1"
          ],
          "operationId": "ApplicationClusterPackage",
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Apicontroller1ApplicationClusterPackage"
                  }
                }
              },
              "text/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Apicontroller1ApplicationClusterPackage"
                  }
                }
              },
              "application/*+json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Apicontroller1ApplicationClusterPackage"
                  }
                }
              }
            }
          },
          "responses": {
            "200": {
              "description": "Success"
            }
          }
        }
      },
      "/api/import/controller1/BackupPolicy": {
        "post": {
          "tags": [
            "controller1"
          ],
          "operationId": "BackupPolicy",
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Apicontroller1BackupPolicy"
                  }
                }
              },
              "text/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Apicontroller1BackupPolicy"
                  }
                }
              },
              "application/*+json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Apicontroller1BackupPolicy"
                  }
                }
              }
            }
          },
          "responses": {
            "200": {
              "description": "Success"
            }
          }
        }
      },
      "/api/import/controller1/BladeEnclosure": {
        "post": {
          "tags": [
            "controller1"
          ],
          "requestBody": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Apicontroller1BladeEnclosure"
                  }
                }
              },
              "text/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Apicontroller1BladeEnclosure"
                  }
                }
              },
              "application/*+json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Apicontroller1BladeEnclosure"
                  }
                }
              }
            }
          },
          "responses": {
            "200": {
              "description": "Success"
            }
          }
        }
      }
    },
    "components": {
      "schemas": {
        "Apicontroller1ApplicationClusterPackage": {
          "type": "object",
          "properties": {
            "id": {
              "type": "integer",
              "format": "int32"
            },
            "name": {
              "type": "string",
              "nullable": true
            },
            "code": {
              "type": "string",
              "nullable": true
            },
            "description": {
              "type": "string",
              "nullable": true
            },
            "startDate": {
              "type": "string",
              "format": "date-time",
              "nullable": true
            },
            "endDate": {
              "type": "string",
              "format": "date-time",
              "nullable": true
            },
            "status": {
              "type": "string",
              "nullable": true
            },
            "owner": {
              "type": "string",
              "nullable": true
            },
            "preferredNode": {
              "type": "string",
              "nullable": true
            },
            "applicationImpact": {
              "type": "integer",
              "format": "int32"
            },
            "supplier": {
              "type": "string",
              "nullable": true
            },
            "bil": {
              "type": "string",
              "nullable": true
            },
            "supportHours": {
              "type": "string",
              "nullable": true
            },
            "externalreference": {
              "type": "string",
              "nullable": true
            },
            "importStatus": {
              "type": "string",
              "nullable": true
            },
            "globalSession": {
              "type": "string",
              "nullable": true
            },
            "rfsReference": {
              "type": "string",
              "nullable": true
            },
            "logTime": {
              "type": "string",
              "format": "date-time"
            }
          },
          "additionalProperties": false
        },
        "Apicontroller1BackupPolicy": {
          "type": "object",
          "properties": {
            "id": {
              "type": "integer",
              "description": "Auto generated : do not fill out",
              "format": "int32"
            },
            "name": {
              "type": "string",
              "nullable": true
            },
            "code": {
              "type": "string",
              "nullable": true
            },
            "description": {
              "type": "string",
              "nullable": true
            },
            "startDate": {
              "type": "string",
              "format": "date-time",
              "nullable": true
            },
            "endDate": {
              "type": "string",
              "format": "date-time",
              "nullable": true
            },
            "status": {
              "type": "string",
              "description": "values (in production,archived)",
              "nullable": true
            },
            "owner": {
              "type": "string",
              "nullable": true
            },
            "applicationImpact": {
              "type": "integer",
              "format": "int32"
            },
            "backupPolicyType": {
              "type": "string",
              "nullable": true
            },
            "retention": {
              "type": "string",
              "nullable": true
            },
            "externalreference": {
              "type": "string",
              "description": "3th part CI unique identifier",
              "nullable": true
            },
            "importStatus": {
              "type": "string",
              "nullable": true
            },
            "globalSession": {
              "type": "string",
              "description": "Unique identifier for the calling session",
              "nullable": true
            },
            "rfsReference": {
              "type": "string",
              "nullable": true
            },
            "logTime": {
              "type": "string",
              "description": "Auto generated : do not fill out",
              "format": "date-time"
            }
          },
          "additionalProperties": false
        },
        "Apicontroller1BladeEnclosure": {
          "type": "object",
          "properties": {
            "id": {
              "type": "integer",
              "format": "int32"
            },
            "name": {
              "type": "string",
              "nullable": true
            },
            "code": {
              "type": "string",
              "nullable": true
            },
            "description": {
              "type": "string",
              "nullable": true
            },
            "startDate": {
              "type": "string",
              "format": "date-time",
              "nullable": true
            },
            "endDate": {
              "type": "string",
              "format": "date-time",
              "nullable": true
            },
            "status": {
              "type": "string",
              "description": "Values (In Production,In Repair/Maintenance,Ordered,Out of Production,\r\nPre-Production,\r\nRemoved,\r\nReserved,\r\nScrapped)",
              "nullable": true
            },
            "owner": {
              "type": "string",
              "nullable": true
            },
            "applicationImpact": {
              "type": "integer",
              "format": "int32"
            },
            "endOfSupport": {
              "type": "string",
              "format": "date-time",
              "nullable": true
            },
            "model": {
              "type": "string",
              "nullable": true
            },
            "productNumber": {
              "type": "string",
              "nullable": true
            },
            "serialNumber": {
              "type": "string",
              "nullable": true
            },
            "supplier": {
              "type": "string",
              "nullable": true
            },
            "primaryIpaddress": {
              "type": "string",
              "nullable": true
            },
            "bil": {
              "type": "string",
              "nullable": true
            },
            "supportHours": {
              "type": "string",
              "nullable": true
            },
            "externalreference": {
              "type": "string",
              "nullable": true
            },
            "importStatus": {
              "type": "string",
              "nullable": true
            },
            "globalSession": {
              "type": "string",
              "nullable": true
            },
            "rfsReference": {
              "type": "string",
              "nullable": true
            },
            "logTime": {
              "type": "string",
              "format": "date-time"
            }
          },
          "additionalProperties": false
        }
      }
    }
  }
```
