### ISSUE TITLE
Profile conflict issue in AppService

### ISSUE THREAD

**Issue by markcowl** [Azure/autorest.powershell#192]
Using this appconfiguration:
https://github.com/markcowl/azure-powershell/blob/generation/src/AppService/readme.md

The following error occurs:
```
PS C:\td\azure-powershell\src\AppService> autorest
AutoRest code generation utility [version: 3.0.5163; node: v10.15.1]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\markcowl\.autorest\@microsoft.azure_autorest-core@3.0.5402\node_modules\@microsof
t.azure\autorest-core\dist' (3.0.5402)
   Loading AutoRest extension '@microsoft.azure/autorest.powershell' (beta->2.0.343)
   Loading AutoRest extension '@microsoft.azure/autorest.remodeler' (beta->2.0.211)
   Loading AutoRest extension '@microsoft.azure/autorest.csharp-v2' (beta->2.0.225)
C:\Users\markcowl\.autorest\@microsoft.azure_autorest-core@3.0.5402\node_modules\@microsoft.azure\autorest-core\dist\lib\
pipeline\pipeline.js - FAILURE {}
Process() cancelled due to exception : Deduplicator: There's a conflict in profile data. There should be a single path ap
i-version per profile. / Error: Deduplicator: There's a conflict in profile data. There should be a single path api-versi
on per profile.
    at getMergedProfilesMetadata (/node_modules/@microsoft.azure/deduplication/dist/main.js:352:19)
    at Deduplicator.deduplicatePaths (/node_modules/@microsoft.azure/deduplication/dist/main.js:148:40)
    at Deduplicator.init (/node_modules/@microsoft.azure/deduplication/dist/main.js:77:26)
    at Deduplicator.get output [as output] (/node_modules/@microsoft.azure/deduplication/dist/main.js:331:18)
    at deduplicate (C:\Users\markcowl\.autorest\@microsoft.azure_autorest-core@3.0.5402\node_modules\@microsoft.azure\aut
orest-core\dist\lib\pipeline\plugins\deduplicator.js:15:82)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  Error: Deduplicator: There's a conflict in profile data. There should be a single path api-version per profile.
```

**Comment by fearthecowboy** [comment]
Same thing as #188 -- deduplicator fix required
