### ISSUE TITLE
Namer error when generating multi-api version of DNS

### ISSUE THREAD

**Issue by markcowl** [Azure/autorest.powershell#194]
Using this spec: 
https://github.com/markcowl/azure-powershell/blob/generation/src/Dns/readme.md
This error:
```
    - oai3-subset-schema-reduced doc... ($)
PLUGIN FAILURE: Invalid Version: 1.0, TypeError: Invalid Version: 1.0
    at new SemVer (C:\Users\markcowl\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.225\node_modules\semver\semver.js:323:11)
    at compare (C:\Users\markcowl\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.225\node_modules\semver\semver.js:614:10)
    at Function.lt (C:\Users\markcowl\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.225\node_modules\semver\semver.js:648:10)
    at lt (C:\Users\markcowl\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.225\node_modules\@microsoft.azure\codegen\src\apiversion.ts:19:17)
    at lowest (C:\Users\markcowl\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.225\node_modules\@microsoft.azure\codegen\src\apiversion.ts:28:10)
    at Object.minimum (C:\Users\markcowl\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.225\node_modules\@microsoft.azure\codegen\src\apiversion.ts:39:14)
    at setSchemaNames (C:\Users\markcowl\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.225\node_modules\@microsoft.azure\autorest.csharp-v2\src\plugin-namer.ts:38:28)
    at nameStuffRight (C:\Users\markcowl\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.225\node_modules\@microsoft.azure\autorest.csharp-v2\src\plugin-namer.ts:137:3), {}
FATAL: TypeError: Invalid Version: 1.0
C:\Users\markcowl\.autorest\@microsoft.azure_autorest-core@3.0.5402\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js - FAILURE {}
Process() cancelled due to exception : Plugin csnamer reported failure. / Error: Plugin csnamer reported failure.
    at C:\Users\markcowl\.autorest\@microsoft.azure_autorest-core@3.0.5402\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\external.js:26:19
  Error: Plugin csnamer reported failure.
```

**Comment by NelsonDaniel** [comment]
This is solved. Another issue: https://github.com/Azure/autorest.powershell/issues/259
