### ISSUE TITLE
Cannot generate Authorization with multiple API versions

### ISSUE THREAD

**Issue by cormacpayne** [Azure/autorest.powershell#200]
Running `autorest` on the following configuration results in an exception:

```
# AutoRest Configuration for Resources

> see https://aka.ms/autorest

``` yaml
require:
  - $(this-folder)/../readme.azure.md
  - https://raw.githubusercontent.com/NelsonDaniel/azure-rest-api-specs/multiapi/specification/authorization/resource-manager/readme.enable-multi-api.md
  - https://raw.githubusercontent.com/NelsonDaniel/azure-rest-api-specs/multiapi/specification/authorization/resource-manager/readme.md

service-name: Resources
subject-prefix: ''
module-version: 0.0.1
skip-model-cmdlets: true
title: ResourceManagementClient
profile:
  - hybrid-2019
  - latest-2019-04-01
    ```
```

Corresponding exception:

```
C:\Users\corm\.autorest\@microsoft.azure_autorest-core@3.0.5402\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js - FAILURE {}
Process() cancelled due to exception : Deduplicator: There's a conflict in profile data. There should be a single path api-version per profile. / Error: Deduplicator: There's a conflict in profile data. There should be a single path api-version per profile.
    at getMergedProfilesMetadata (/node_modules/@microsoft.azure/deduplication/dist/main.js:352:19)
    at Deduplicator.deduplicatePaths (/node_modules/@microsoft.azure/deduplication/dist/main.js:148:40)
    at Deduplicator.init (/node_modules/@microsoft.azure/deduplication/dist/main.js:77:26)
    at Deduplicator.get output [as output] (/node_modules/@microsoft.azure/deduplication/dist/main.js:331:18)
    at deduplicate (C:\Users\corm\.autorest\@microsoft.azure_autorest-core@3.0.5402\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\deduplicator.js:15:82)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  Error: Deduplicator: There's a conflict in profile data. There should be a single path api-version per profile.
```

**Comment by cormacpayne** [comment]
Fixed! :shipit:
