### ISSUE TITLE
Cannot generate Management due to issue in spec

### ISSUE THREAD

**Issue by cormacpayne** [Azure/autorest.powershell#202]
Running `autorest` on the following configuration results in an exception:

```
# AutoRest Configuration for Resources

> see https://aka.ms/autorest

``` yaml
require:
  - $(this-folder)/../readme.azure.md
  - https://raw.githubusercontent.com/NelsonDaniel/azure-rest-api-specs/multiapi/specification/managementgroups/resource-manager/readme.enable-multi-api.md
  - https://raw.githubusercontent.com/NelsonDaniel/azure-rest-api-specs/multiapi/specification/managementgroups/resource-manager/readme.md

service-name: Resources
subject-prefix: ''
module-version: 0.0.1
skip-model-cmdlets: true
title: ResourceManagementClient
profile:
  - hybrid-2019
  - latest-2019-04-01
directive:
  - where:
      subject: Application(.*)
    set:
      subject: ManagedApplication$1
    ```
```

Corresponding exception:

```
C:\Users\corm\.autorest\@microsoft.azure_autorest-core@3.0.5402\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js - FAILURE {}
Process() cancelled due to exception : Assignment: Value 'x-ms-enum' may not be undefined. / Error: Assignment: Value 'x-ms-enum' may not be undefined.
    at Object.set (/node_modules/@microsoft.azure/datastore/dist/graph-builder.js:39:23)
    at EnumDeduplicator.clone (/node_modules/@microsoft.azure/datastore/dist/processor.js:62:31)
    at EnumDeduplicator.finish (C:\Users\corm\.autorest\@microsoft.azure_autorest-core@3.0.5402\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\enum-deduplication.js:81:18)
    at EnumDeduplicator.runProcess (/node_modules/@microsoft.azure/datastore/dist/processor.js:78:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  Error: Assignment: Value 'x-ms-enum' may not be undefined.
```

**Comment by fearthecowboy** [comment]
Fixed, right @cormacpayne ?

**Comment by cormacpayne** [comment]
Yep, just confirmed this was fixed :shipit:
