### ISSUE TITLE
FATAL: Error: Unknown Model. Fatal.

### ISSUE THREAD

**Issue by NakulSabharwal** [Azure/autorest.powershell#205]
Getting error `ERROR (UnknownJsonType/LLCS2000): Schema 'microsoft.graph.calendarColor' is declared with invalid type 'undefined' when given input the attached yaml file.

`autorest --powershell --input-file:openapi-groups-cal.yml`

[openapi-groups-cal.zip](https://github.com/Azure/autorest.powershell/files/3056979/openapi-groups-cal.zip)

`
```
C:\Users\nasabhar\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.227\node_modules\@microsoft.azure\autorest.csharp-v2\dist\plugin-llcsharp.js - Error: Unknown Model. Fatal.
    at SchemaDefinitionResolver.resolveTypeDeclaration (C:\Users\nasabhar\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.227\node_modules\@microsoft.azure\autorest.csharp-v2\src\schema\schema-resolver.ts:206:11)
    at ModelsNamespace.resolveTypeDeclaration (C:\Users\nasabhar\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.227\node_modules\@microsoft.azure\autorest.csharp-v2\src\model\namespace.ts:69:30)
    at new ModelsNamespace (C:\Users\nasabhar\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.227\node_modules\@microsoft.azure\autorest.csharp-v2\src\model\namespace.ts:56:12)
    at Project.init (C:\Users\nasabhar\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.227\node_modules\@microsoft.azure\autorest.csharp-v2\src\project.ts:75:46)/Unknown Model. Fatal.
PLUGIN FAILURE: Unknown Model. Fatal., Error: Unknown Model. Fatal.
    at SchemaDefinitionResolver.resolveTypeDeclaration (C:\Users\nasabhar\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.227\node_modules\@microsoft.azure\autorest.csharp-v2\src\schema\schema-resolver.ts:206:11)
    at ModelsNamespace.resolveTypeDeclaration (C:\Users\nasabhar\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.227\node_modules\@microsoft.azure\autorest.csharp-v2\src\model\namespace.ts:69:30)
    at new ModelsNamespace (C:\Users\nasabhar\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.227\node_modules\@microsoft.azure\autorest.csharp-v2\src\model\namespace.ts:56:12)
    at Project.init (C:\Users\nasabhar\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.227\node_modules\@microsoft.azure\autorest.csharp-v2\src\project.ts:75:46), {}
FATAL: Error: Unknown Model. Fatal.
C:\Users\nasabhar\.autorest\@microsoft.azure_autorest-core@3.0.5402\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js - FAILURE {}
(node:15104) UnhandledPromiseRejectionWarning: Error: Plugin llcsharp reported failure.
    at C:\Users\nasabhar\.autorest\@microsoft.azure_autorest-core@3.0.5402\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\external.js:26:19
(node:15104) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 30)
(node:15104) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:15104) UnhandledPromiseRejectionWarning: Error: Plugin llcsharp reported failure.
    at C:\Users\nasabhar\.autorest\@microsoft.azure_autorest-core@3.0.5402\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\external.js:26:19
(node:15104) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 31)

ERROR (UnknownJsonType/LLCS2000): Schema 'microsoft.graph.calendarColor' is declared with invalid type 'undefined'
    - code-model-v3.yaml:6493:4
C:\Users\nasabhar\.autorest\@microsoft.azure_autorest.powershell@2.0.347\node_modules\@microsoft.azure\autorest.powershell\dist\plugin-powershell.js - FAILURE  {} Error: Unknown Model. Fatal.
    at SchemaDefinitionResolver.resolveTypeDeclaration (C:\Users\nasabhar\.autorest\@microsoft.azure_autorest.powershell@2.0.347\node_modules\@microsoft.azure\autorest.csharp-v2\src\schema\schema-resolver.ts:206:11)
    at CmdletClass.addPowershellParameters (C:\Users\nasabhar\.autorest\@microsoft.azure_autorest.powershell@2.0.347\node_modules\@microsoft.azure\autorest.powershell\cmdlet-class.ts:662:78)
    at new CmdletClass (C:\Users\nasabhar\.autorest\@microsoft.azure_autorest.powershell@2.0.347\node_modules\@microsoft.azure\autorest.powershell\cmdlet-class.ts:63:10)
    at new CmdletNamespace (C:\Users\nasabhar\.autorest\@microsoft.azure_autorest.powershell@2.0.347\node_modules\@microsoft.azure\autorest.powershell\namespaces\cmdlet.ts:24:21)
    at Project.init (C:\Users\nasabhar\.autorest\@microsoft.azure_autorest.powershell@2.0.347\node_modules\@microsoft.azure\autorest.powershell\project.ts:150:38)
PLUGIN FAILURE: Unknown Model. Fatal., Error: Unknown Model. Fatal.
    at SchemaDefinitionResolver.resolveTypeDeclaration (C:\Users\nasabhar\.autorest\@microsoft.azure_autorest.powershell@2.0.347\node_modules\@microsoft.azure\autorest.csharp-v2\src\schema\schema-resolver.ts:206:11)
    at CmdletClass.addPowershellParameters (C:\Users\nasabhar\.autorest\@microsoft.azure_autorest.powershell@2.0.347\node_modules\@microsoft.azure\autorest.powershell\cmdlet-class.ts:662:78)
    at new CmdletClass (C:\Users\nasabhar\.autorest\@microsoft.azure_autorest.powershell@2.0.347\node_modules\@microsoft.azure\autorest.powershell\cmdlet-class.ts:63:10)
    at new CmdletNamespace (C:\Users\nasabhar\.autorest\@microsoft.azure_autorest.powershell@2.0.347\node_modules\@microsoft.azure\autorest.powershell\namespaces\cmdlet.ts:24:21)
    at Project.init (C:\Users\nasabhar\.autorest\@microsoft.azure_autorest.powershell@2.0.347\node_modules\@microsoft.azure\autorest.powershell\project.ts:150:38), {}
FATAL: Error: Unknown Model. Fatal.
C:\Users\nasabhar\.autorest\@microsoft.azure_autorest-core@3.0.5402\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js - FAILURE {}
Process() cancelled due to exception : Plugin llcsharp reported failure. / Error: Plugin llcsharp reported failure.
    at C:\Users\nasabhar\.autorest\@microsoft.azure_autorest-core@3.0.5402\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\external.js:26:19
  Error: Plugin llcsharp reported failure.
```

**Comment by kevinblumenfeld** [comment]
@NakulSabharwal can I ask what you did to fix this issue?

**Comment by potatoqualitee** [comment]
denvercoder9, what did you seeeee?!
