### ISSUE TITLE
Error when generating KeyVault dataplane cmdlets

### ISSUE THREAD

**Issue by cormacpayne** [Azure/autorest.powershell#286]
When running `autorest` on [this `readme.md`](https://gist.github.com/cormacpayne/07ed58ad658a7a63ae1bf9a6456c69d7) file, I receive the following error:

```
Note: model  Error has a circular reference, and we're skipping inlining.
  KeyVaultError::error => Error::innererror
Note: model  Error has a circular reference, and we're skipping inlining.
  CertificateOperation::error => Error::innererror
C:\Users\corm\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.283\node_modules\@microsoft.azure\autorest.csharp-v2\dist\plugin-llcsharp.js - TypeError: Cannot read property 'declaration' of undefined
    at InterfaceProperty.get declaration [as declaration] (C:\Users\corm\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.283\node_modules\@microsoft.azure\codegen-csharp\interface-property.ts:23:25)
    at properties.properties.sort.map.m (C:\Users\corm\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.283\node_modules\@microsoft.azure\codegen-csharp\interface.ts:26:68)
    at Array.map (<anonymous>)
    at ModelInterface.get definition [as definition] (C:\Users\corm\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.283\node_modules\@microsoft.azure\codegen-csharp\interface.ts:26:57)
    at contents.push.interfacesWithSameName.map.each (C:\Users\corm\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.283\node_modules\@microsoft.azure\codegen-csharp\namespace.ts:120:68)
    at Array.map (<anonymous>)
    at ApiVersionNamespace.writeFiles (C:\Users\corm\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.283\node_modules\@microsoft.azure\codegen-csharp\namespace.ts:120:51)
    at children.namespaces.map (C:\Users\corm\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.283\node_modules\@microsoft.azure\codegen-csharp\namespace.ts:109:71)
    at Array.map (<anonymous>)
    at ModelsNamespace.writeFiles (C:\Users\corm\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.283\node_modules\@microsoft.azure\codegen-csharp\namespace.ts:109:38)/Cannot read property 'declaration' of undefined
PLUGIN FAILURE: Cannot read property 'declaration' of undefined, TypeError: Cannot read property 'declaration' of undefined
    at InterfaceProperty.get declaration [as declaration] (C:\Users\corm\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.283\node_modules\@microsoft.azure\codegen-csharp\interface-property.ts:23:25)
    at properties.properties.sort.map.m (C:\Users\corm\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.283\node_modules\@microsoft.azure\codegen-csharp\interface.ts:26:68)
    at Array.map (<anonymous>)
    at ModelInterface.get definition [as definition] (C:\Users\corm\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.283\node_modules\@microsoft.azure\codegen-csharp\interface.ts:26:57)
    at contents.push.interfacesWithSameName.map.each (C:\Users\corm\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.283\node_modules\@microsoft.azure\codegen-csharp\namespace.ts:120:68)
    at Array.map (<anonymous>)
    at ApiVersionNamespace.writeFiles (C:\Users\corm\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.283\node_modules\@microsoft.azure\codegen-csharp\namespace.ts:120:51)
    at children.namespaces.map (C:\Users\corm\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.283\node_modules\@microsoft.azure\codegen-csharp\namespace.ts:109:71)
    at Array.map (<anonymous>)
    at ModelsNamespace.writeFiles (C:\Users\corm\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.283\node_modules\@microsoft.azure\codegen-csharp\namespace.ts:109:38), {}
FATAL: TypeError: Cannot read property 'declaration' of undefined
C:\Users\corm\.autorest\@microsoft.azure_autorest-core@3.0.5447\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js - FAILURE {}
(node:15392) UnhandledPromiseRejectionWarning: Error: Plugin llcsharp reported failure.
    at C:\Users\corm\.autorest\@microsoft.azure_autorest-core@3.0.5447\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\external.js:26:19
(node:15392) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 54)
(node:15392) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:15392) UnhandledPromiseRejectionWarning: Error: Plugin llcsharp reported failure.
    at C:\Users\corm\.autorest\@microsoft.azure_autorest-core@3.0.5447\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\external.js:26:19
(node:15392) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 55)
Process() cancelled due to exception : Plugin llcsharp reported failure. / Error: Plugin llcsharp reported failure.
    at C:\Users\corm\.autorest\@microsoft.azure_autorest-core@3.0.5447\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\external.js:26:19
```

**Comment by fearthecowboy** [comment]
@cormacpayne - This is fixed in autorest.powershell 2.0.440. -- `autorest --reset` and try it now.

**Comment by cormacpayne** [comment]
Fix has been confirmed 🎉
