### ISSUE TITLE
Process() cancelled due to exception : Invalid Version: 1 / TypeError: Invalid Version: 1

### ISSUE THREAD

**Issue by grock90** [Azure/autorest.powershell#330]
I get the following FAILURE/ERROR when generating a powershell client, however I am able to successfully create other clients (nodejs,csharp,python) with the same swagger.json file.   I appreciate any help in how to workaround this issue. 

autorest --input-file:file:///C:/Build/product-card-service/ProductCard.Service/swagger.json --output-folder:./ --message-format:json  --powershell --debug

AutoRest code generation utility [version: 3.0.5200; node: v11.3.0, max-memory: 8192 gb]

C:\Users\grock90\.autorest\@microsoft.azure_autorest-core@3.0.5456\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js - FAILURE {}
Process() cancelled due to exception : Invalid Version: 1 / TypeError: Invalid Version: 1
    at new SemVer (/node_modules/semver/semver.js:323:11)
    at compare (/node_modules/semver/semver.js:614:10)
    at Function.gt (/node_modules/semver/semver.js:643:10)
    at gt (/node_modules/@microsoft.azure/codegen/dist/apiversion.js:70:19)
    at highest (/node_modules/@microsoft.azure/codegen/dist/apiversion.js:78:12)
    at Object.maximum (/node_modules/@microsoft.azure/codegen/dist/apiversion.js:98:18)
    at schemas.sort (C:\Users\grock90\.autorest\@microsoft.azure_autorest-core@3.0.5456\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\subset-schemas-deduplicator.js:55:43)
    at Array.sort (<anonymous>)
    at SubsetSchemaDeduplicator.visitSchemas (C:\Users\gbarnes\.autorest\@microsoft.azure_autorest-core@3.0.5456\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\subset-schemas-deduplicator.js:54:17)
    at SubsetSchemaDeduplicator.visitComponents (C:\Users\gbarnes\.autorest\@microsoft.azure_autorest-core@3.0.5456\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\subset-schemas-deduplicator.js:29:26)
    at SubsetSchemaDeduplicator.process (C:\Users\gbarnes\.autorest\@microsoft.azure_autorest-core@3.0.5456\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\subset-schemas-deduplicator.js:13:26)
    at SubsetSchemaDeduplicator.runProcess (/node_modules/@microsoft.azure/datastore/dist/processor.js:76:28)
  TypeError: Invalid Version: 1
[5.63 s] Shutting Down.
[5.63 s] Exiting.

**Comment by joshspicer** [comment]
Any solution for this @grock90 ?

**Comment by joshspicer** [comment]
It looks like simply adding "v1" or "1" get rejected by the regex when being referenced in other parts of the file (with a `#`). 

 I've gotten it to work by adding a version number like "1.0.0" . I'm unsure if this is intended behavior or not.

**Comment by Selflo** [comment]
I hit the same issue, modify my swagger generation from v1 to v1.0 solved the problem. Thanks.
