### ISSUE TITLE
Compute admin module generation fails with "NewQuotaParameter is not found in the new refs collection" error

### ISSUE THREAD

**Issue by seyadava** [Azure/autorest.powershell#361]
I have created following readme files in powershell and specs repos:
Powershell repo:
https://github.com/seyadava/azure-powershell/blob/azscomputegen/src/Compute/Compute/readme.md
https://github.com/seyadava/azure-powershell/blob/azscomputegen/src/readme.azurestack.md

Specs repo:
https://github.com/seyadava/azure-rest-api-specs/blob/azscomputegen/specification/azsadmin/resource-manager/compute/readme.md
https://github.com/seyadava/azure-rest-api-specs/blob/azscomputegen/specification/azsadmin/resource-manager/compute/readme.azsautogen.md

I run `autorest` command with no parameters from the directory that contains https://github.com/seyadava/azure-powershell/blob/azscomputegen/src/Compute/Compute/readme.md file. It fails with the following error: 
C:\Users\username\.autorest\@microsoft.azure_autorest-core@3.0.5456\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js - FAILURE {}
Process() cancelled due to exception : $ref to original location 'https://github.com/seyadava/azure-rest-api-specs/blob/azscomputegen/specification/azsadmin/resource-manager/compute/Microsoft.Compute.Admin/preview/2018-02-09/Quotas.json#/components/parameters/NewQuotaParameter' is not found in the new refs collection / Error: $ref to original location 'https://github.com/seyadava/azure-rest-api-specs/blob/azscomputegen/specification/azsadmin/resource-manager/compute/Microsoft.Compute.Admin/preview/2018-02-09/Quotas.json#/components/parameters/NewQuotaParameter' is not found in the new refs collection
    at MultiAPIMerger.updateRefs (C:\Users\seyadava\.autorest\@microsoft.azure_autorest-core@3.0.5456\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\merger.js:230:31)
    at MultiAPIMerger.updateRefs (C:\Users\seyadava\.autorest\@microsoft.azure_autorest-core@3.0.5456\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\merger.js:234:22)
    at MultiAPIMerger.updateRefs (C:\Users\seyadava\.autorest\@microsoft.azure_autorest-core@3.0.5456\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\merger.js:234:22)
    at MultiAPIMerger.updateRefs (C:\Users\seyadava\.autorest\@microsoft.azure_autorest-core@3.0.5456\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\merger.js:234:22)
    at MultiAPIMerger.updateRefs (C:\Users\seyadava\.autorest\@microsoft.azure_autorest-core@3.0.5456\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\merger.js:234:22)
    at MultiAPIMerger.finish (C:\Users\seyadava\.autorest\@microsoft.azure_autorest-core@3.0.5456\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\merger.js:217:14)
    at MultiAPIMerger.runProcess (/node_modules/@microsoft.azure/datastore/dist/processor.js:78:24)
  Error: $ref to original location 'https://github.com/seyadava/azure-rest-api-specs/blob/azscomputegen/specification/azsadmin/resource-manager/compute/Microsoft.Compute.Admin/preview/2018-02-09/Quotas.json#/components/parameters/NewQuotaParameter' is not found in the new refs collection

**Comment by bganapa** [comment]
This has been fixed
