### ISSUE TITLE
ERROR (UnknownJsonType/LLCS2000): Schema 'BasicAuthApplicationName' is declared with invalid type 'undefined'

### ISSUE THREAD

**Issue by kevinblumenfeld** [Azure/autorest.powershell#385]
Attempting to generate PowerShell module with spec: https://github.com/okta/okta-sdk-java/blob/master/src/swagger/api.yaml

```
PS C:\Scripts\PoshOkta> autorest --reset
AutoRest code generation utility [version: 3.0.5221; node: v10.16.0, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest


Cleared the AutoRest extension folder.
On the next run, extensions will be reacquired from the repository.
 autorest --powershell --input-file:./okta.yaml --clear-output-folder
AutoRest code generation utility [version: 3.0.5221; node: v10.16.0, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest-core@3.0.5504\node_modules\@microsoft.azure\autorest-core\dist' (3.0.5504)
   Installing AutoRest extension '@microsoft.azure/autorest.powershell' (beta)
   Installed AutoRest extension '@microsoft.azure/autorest.powershell' (beta->2.0.547)
   Installing AutoRest extension '@microsoft.azure/autorest.remodeler' (beta)
   Installed AutoRest extension '@microsoft.azure/autorest.remodeler' (beta->2.0.317)
   Installing AutoRest extension '@microsoft.azure/autorest.csharp-v2' (beta)
   Installed AutoRest extension '@microsoft.azure/autorest.csharp-v2' (beta->2.0.350)
WARNING (): Operation forgot/password is inferred without finding action.
    - code-model-v3-tweakcodemodel.yaml:1:1

WARNING (): Operation expire/password is inferred without finding action.
    - code-model-v3-tweakcodemodel.yaml:1:1

WARNING (): Operation unsuspend/user is inferred without finding action.
    - code-model-v3-tweakcodemodel.yaml:1:1

ERROR (UnknownJsonType/LLCS2000): Schema 'BasicAuthApplicationName' is declared with invalid type 'undefined'
    - code-model-v3-modifiers.yaml:1:1
C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.350\node_modules\@microsoft.azure\autorest.csharp-v2\dist\plugin-llcsharp.js - Error: Unknown Model. Fatal.
    at SchemaDefinitionResolver.resolveTypeDeclaration (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.350\node_modules\@microsoft.azure\autorest.csharp-v2\schema\schema-resolver.ts:145:11)
    at ModelsNamespace.resolveTypeDeclaration (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.350\node_modules\@microsoft.azure\autorest.csharp-v2\model\namespace.ts:69:30)
    at ModelInterface.init (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.350\node_modules\@microsoft.azure\autorest.csharp-v2\model\interface.ts:111:58)
    at new ModelClass (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.350\node_modules\@microsoft.azure\autorest.csharp-v2\model\model-class.ts:113:198)
    at ModelsNamespace.resolveTypeDeclaration (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.350\node_modules\@microsoft.azure\autorest.csharp-v2\model\namespace.ts:80:65)
    at new ModelsNamespace (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.350\node_modules\@microsoft.azure\autorest.csharp-v2\model\namespace.ts:56:12)
    at Project.init (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.350\node_modules\@microsoft.azure\autorest.csharp-v2\project.ts:69:46)/Unknown Model. Fatal.
PLUGIN FAILURE: Unknown Model. Fatal., Error: Unknown Model. Fatal.
    at SchemaDefinitionResolver.resolveTypeDeclaration (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.350\node_modules\@microsoft.azure\autorest.csharp-v2\schema\schema-resolver.ts:145:11)
    at ModelsNamespace.resolveTypeDeclaration (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.350\node_modules\@microsoft.azure\autorest.csharp-v2\model\namespace.ts:69:30)
    at ModelInterface.init (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.350\node_modules\@microsoft.azure\autorest.csharp-v2\model\interface.ts:111:58)
    at new ModelClass (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.350\node_modules\@microsoft.azure\autorest.csharp-v2\model\model-class.ts:113:198)
    at ModelsNamespace.resolveTypeDeclaration (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.350\node_modules\@microsoft.azure\autorest.csharp-v2\model\namespace.ts:80:65)
    at new ModelsNamespace (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.350\node_modules\@microsoft.azure\autorest.csharp-v2\model\namespace.ts:56:12)
    at Project.init (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.csharp-v2@2.0.350\node_modules\@microsoft.azure\autorest.csharp-v2\project.ts:69:46), {}
FATAL: Error: Unknown Model. Fatal.
C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest-core@3.0.5504\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js - FAILURE {}

ERROR (UnknownJsonType/LLCS2000): Schema 'ApplicationSettingsApplication' is declared with invalid type 'undefined'
    - code-model-v3-add-azure-completers.yaml:1:1
C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.powershell@2.0.547\node_modules\@microsoft.azure\autorest.powershell\dist\plugin-powershell.js - FAILURE  {} Error: Unknown Model. Fatal.
    at PSSchemaResolver.resolveTypeDeclaration (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.powershell@2.0.547\node_modules\@microsoft.azure\autorest.csharp-v2\schema\schema-resolver.ts:145:11)
    at PSSchemaResolver.resolveTypeDeclaration (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.powershell@2.0.547\node_modules\@microsoft.azure\autorest.powershell\project.ts:45:18)
    at CmdletClass.addPowershellParameters (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.powershell@2.0.547\node_modules\@microsoft.azure\autorest.powershell\cmdlet-class.ts:886:74)
    at CmdletClass.init (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.powershell@2.0.547\node_modules\@microsoft.azure\autorest.powershell\cmdlet-class.ts:133:10)
    at CmdletNamespace.init (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.powershell@2.0.547\node_modules\@microsoft.azure\autorest.powershell\namespaces\cmdlet.ts:31:110)
PLUGIN FAILURE: Unknown Model. Fatal., Error: Unknown Model. Fatal.
    at PSSchemaResolver.resolveTypeDeclaration (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.powershell@2.0.547\node_modules\@microsoft.azure\autorest.csharp-v2\schema\schema-resolver.ts:145:11)
    at PSSchemaResolver.resolveTypeDeclaration (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.powershell@2.0.547\node_modules\@microsoft.azure\autorest.powershell\project.ts:45:18)
    at CmdletClass.addPowershellParameters (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.powershell@2.0.547\node_modules\@microsoft.azure\autorest.powershell\cmdlet-class.ts:886:74)
    at CmdletClass.init (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.powershell@2.0.547\node_modules\@microsoft.azure\autorest.powershell\cmdlet-class.ts:133:10)
    at CmdletNamespace.init (C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest.powershell@2.0.547\node_modules\@microsoft.azure\autorest.powershell\namespaces\cmdlet.ts:31:110), {}
FATAL: Error: Unknown Model. Fatal.
C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest-core@3.0.5504\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js - FAILURE {}
Process() cancelled due to exception : Plugin llcsharp reported failure. / Error: Plugin llcsharp reported failure.
    at C:\Users\kevin.blumenfeld\.autorest\@microsoft.azure_autorest-core@3.0.5504\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\external.js:26:19
  Error: Plugin llcsharp reported failure.```

**Comment by fearthecowboy** [comment]
That spec isn't near complete enough to generate code from...

Models like this: 

``` yaml
 BasicAuthApplication:
    properties:
      credentials:
        $ref: '#/definitions/SchemeApplicationCredentials'
      name:
        default: template_basic_auth
      settings:
        $ref: '#/definitions/BasicApplicationSettings'
    x-okta-defined-as:
      name: template_basic_auth
    x-okta-parent: '#/definitions/Application'
    x-okta-tags:
      - Application
```

have no types for their properties

`name` with just a `default` isn't very useful at all.

`default` declares the value used if the client doesn't send anything. 

I have no idea what that model is supposed to do.


and all the `x-*` extensions aren't going to be used for anything.

**Comment by bdemers** [comment]
@fearthecowboy +1

We borrowed a little from the v3 spec and defined some extensions to support inheritance/discriminators: https://github.com/okta/okta-sdk-java/blob/master/src/swagger/api.yaml#L2829-L2838

That said, we probably need to make this spec valid for folks NOT using our extensions.
Thanks for the comment, go ahead and close this issue.

- one of the authors of said spec
