### ISSUE TITLE
Can not generate AppServices module

### ISSUE THREAD

**Issue by markcowl** [Azure/autorest.powershell#411]
Error in the deduplicator, caused when attempting to generate the AppServices module at:
https://github.com/Azure/azure-powershell/blob/generation/src/AppService/readme.md

The error is:

```
$ autorest
AutoRest code generation utility [version: 3.0.5199; node: v10.15.1, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\markcowl\.autorest\@microsoft.azure_autorest-core@3.0.5525\node_modules\@microsoft.azure\autorest-core\dist' (3.0.5525)
(node:23208) ExperimentalWarning: The fs.promises API is experimental
   Installing AutoRest extension '@microsoft.azure/autorest.powershell' (beta)
   Installed AutoRest extension '@microsoft.azure/autorest.powershell' (beta->2.0.576)
   Installing AutoRest extension '@microsoft.azure/autorest.remodeler' (beta)
   Installed AutoRest extension '@microsoft.azure/autorest.remodeler' (beta->2.0.326)
   Installing AutoRest extension '@microsoft.azure/autorest.csharp-v2' (beta)
   Installed AutoRest extension '@microsoft.azure/autorest.csharp-v2' (beta->2.0.367)
C:\Users\markcowl\.autorest\@microsoft.azure_autorest-core@3.0.5525\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js - FAILURE {}
Process() cancelled due to exception : Cannot convert undefined or null to object / TypeError: Cannot convert undefined or null to object
    at Function.getOwnPropertyNames (<anonymous>)
    at SubsetSchemaDeduplicator.visitSchemas (C:\Users\markcowl\.autorest\@microsoft.azure_autorest-core@3.0.5525\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\subset-schemas-deduplicator.js:76:53)
    at SubsetSchemaDeduplicator.visitComponents (C:\Users\markcowl\.autorest\@microsoft.azure_autorest-core@3.0.5525\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\subset-schemas-deduplicator.js:29:26)
    at SubsetSchemaDeduplicator.process (C:\Users\markcowl\.autorest\@microsoft.azure_autorest-core@3.0.5525\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\subset-schemas-deduplicator.js:13:26)
    at SubsetSchemaDeduplicator.runProcess (/node_modules/@microsoft.azure/datastore/dist/processor.js:76:28)
  TypeError: Cannot convert undefined or null to object
```

**Comment by MiYanni** [comment]
Fixed: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=68853&view=results
