### ISSUE TITLE
Cannot generate Storage module (Cannot convert undefined to null)

### ISSUE THREAD

**Issue by markcowl** [Azure/autorest.powershell#416]
This is generating the storage module from the configuration here: https://github.com/Azure/azure-powershell/blob/generation/src/Storage/readme.md

This is the error:
```
PS C:\td\azure-powershell\src\Storage> autorest
AutoRest code generation utility [version: 3.0.5199; node: v10.15.1, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\markcowl\.autorest\@microsoft.azure_autorest-core@3.0.5525\node_modules\@microsoft.azure\autorest-core\dist' (3.0.5525)
(node:3008) ExperimentalWarning: The fs.promises API is experimental
   Loading AutoRest extension '@microsoft.azure/autorest.powershell' (beta->2.0.576)
   Loading AutoRest extension '@microsoft.azure/autorest.remodeler' (beta->2.0.326)
   Loading AutoRest extension '@microsoft.azure/autorest.csharp-v2' (beta->2.0.367)
C:\Users\markcowl\.autorest\@microsoft.azure_autorest-core@3.0.5525\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js - FAILURE {}
Process() cancelled due to exception : Cannot convert undefined or null to object / TypeError: Cannot convert undefined or null to object
    at Function.getOwnPropertyNames (<anonymous>)
    at SubsetSchemaDeduplicator.visitSchemas (C:\Users\markcowl\.autorest\@microsoft.azure_autorest-core@3.0.5525\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\subset-schemas-deduplicator.js:76:53)
    at SubsetSchemaDeduplicator.visitComponents (C:\Users\markcowl\.autorest\@microsoft.azure_autorest-core@3.0.5525\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\subset-schemas-deduplicator.js:29:26)
    at SubsetSchemaDeduplicator.process (C:\Users\markcowl\.autorest\@microsoft.azure_autorest-core@3.0.5525\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\subset-schemas-deduplicator.js:13:26)
    at SubsetSchemaDeduplicator.runProcess (/node_modules/@microsoft.azure/datastore/dist/processor.js:76:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  TypeError: Cannot convert undefined or null to object
```

**Comment by markcowl** [comment]
Detailed debug/verbose logs:
```
PS C:\td\azure-powershell\src\Storage> autorest --debug --verbose                                                                                             AutoRest code generation utility [version: 3.0.5199; node: v10.15.1, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Network Enabled: true
Starting @microsoft.azure/autorest-core from C:\Users\markcowl\.autorest\@microsoft.azure_autorest-core@3.0.5525
   Loading AutoRest core      'C:\Users\markcowl\.autorest\@microsoft.azure_autorest-core@3.0.5525\node_modules\@microsoft.azure\autorest-core\dist' (3.0.5525)
(node:26160) ExperimentalWarning: The fs.promises API is experimental
   Including configuration file 'file:///C:/td/azure-powershell/src/Storage/../readme.azure.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/storage/resource-manager/readme.enable-multi-api.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/storage/resource-manager/readme.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/profiles/readme.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/storage/resource-manager/../../../profiles/readme.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/profiles/definitions/hybrid-2018-03-01.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/profiles/definitions/hybrid-2019-03-01.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/profiles/definitions/latest-2019-04-01.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/profiles/definitions/latest-2019-04-24.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/profiles/definitions/latest-2019-04-29.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/profiles/definitions/latest-2019-04-30.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/profiles/definitions/profile-2017-03-09.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/profiles/definitions/stable-2019-01.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/storage/resource-manager/../../../profiles/definitions/hybrid-2018-03-01.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/storage/resource-manager/../../../profiles/definitions/hybrid-2019-03-01.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/storage/resource-manager/../../../profiles/definitions/latest-2019-04-01.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/storage/resource-manager/../../../profiles/definitions/latest-2019-04-24.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/storage/resource-manager/../../../profiles/definitions/latest-2019-04-29.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/storage/resource-manager/../../../profiles/definitions/latest-2019-04-30.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/storage/resource-manager/../../../profiles/definitions/profile-2017-03-09.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/storage/resource-manager/../../../profiles/definitions/stable-2019-01.md'
   Including configuration file 'file:///C:/Users/markcowl/.autorest/@microsoft.azure_autorest-core@3.0.5525/node_modules/@microsoft.azure/autorest-core/resources/directives.md'
   Including configuration file 'file:///C:/Users/markcowl/.autorest/@microsoft.azure_autorest-core@3.0.5525/node_modules/@microsoft.azure/autorest-core/resources/pipeline-merger.md'
   Including configuration file 'file:///C:/Users/markcowl/.autorest/@microsoft.azure_autorest-core@3.0.5525/node_modules/@microsoft.azure/autorest-core/resources/pipeline-composer.md'
   Including configuration file 'file:///C:/Users/markcowl/.autorest/@microsoft.azure_autorest-core@3.0.5525/node_modules/@microsoft.azure/autorest-core/resources/pipeline-tree-shaker.md'
   Including configuration file 'file:///C:/Users/markcowl/.autorest/@microsoft.azure_autorest-core@3.0.5525/node_modules/@microsoft.azure/autorest-core/resources/loader-openapi2.md'
   Including configuration file 'file:///C:/Users/markcowl/.autorest/@microsoft.azure_autorest-core@3.0.5525/node_modules/@microsoft.azure/autorest-core/resources/loader-openapi3.md'
   Including configuration file 'file:///C:/Users/markcowl/.autorest/@microsoft.azure_autorest-core@3.0.5525/node_modules/@microsoft.azure/autorest-core/resources/markdown-documentation.md'
   Including configuration file 'file:///C:/Users/markcowl/.autorest/@microsoft.azure_autorest-core@3.0.5525/node_modules/@microsoft.azure/autorest-core/resources/miscellaneous.md'
   Including configuration file 'file:///C:/Users/markcowl/.autorest/@microsoft.azure_autorest-core@3.0.5525/node_modules/@microsoft.azure/autorest-core/resources/patches.md'
   Including configuration file 'file:///C:/Users/markcowl/.autorest/@microsoft.azure_autorest-core@3.0.5525/node_modules/@microsoft.azure/autorest-core/resources/plugin-powershell.md'
   Including configuration file 'file:///C:/Users/markcowl/.autorest/@microsoft.azure_autorest-core@3.0.5525/node_modules/@microsoft.azure/autorest-core/resources/plugin-azureresourceschema.md'
   Including configuration file 'file:///C:/Users/markcowl/.autorest/@microsoft.azure_autorest-core@3.0.5525/node_modules/@microsoft.azure/autorest-core/resources/plugin-csharp.md'
   Including configuration file 'file:///C:/Users/markcowl/.autorest/@microsoft.azure_autorest-core@3.0.5525/node_modules/@microsoft.azure/autorest-core/resources/plugin-go.md'
   Including configuration file 'file:///C:/Users/markcowl/.autorest/@microsoft.azure_autorest-core@3.0.5525/node_modules/@microsoft.azure/autorest-core/resources/plugin-java.md'
   Including configuration file 'file:///C:/Users/markcowl/.autorest/@microsoft.azure_autorest-core@3.0.5525/node_modules/@microsoft.azure/autorest-core/resources/plugin-nodejs.md'
   Including configuration file 'file:///C:/Users/markcowl/.autorest/@microsoft.azure_autorest-core@3.0.5525/node_modules/@microsoft.azure/autorest-core/resources/plugin-php.md'
   Including configuration file 'file:///C:/Users/markcowl/.autorest/@microsoft.azure_autorest-core@3.0.5525/node_modules/@microsoft.azure/autorest-core/resources/plugin-python.md'
   Including configuration file 'file:///C:/Users/markcowl/.autorest/@microsoft.azure_autorest-core@3.0.5525/node_modules/@microsoft.azure/autorest-core/resources/plugin-ruby.md'
   Including configuration file 'file:///C:/Users/markcowl/.autorest/@microsoft.azure_autorest-core@3.0.5525/node_modules/@microsoft.azure/autorest-core/resources/plugin-typescript.md'
   Including configuration file 'file:///C:/Users/markcowl/.autorest/@microsoft.azure_autorest-core@3.0.5525/node_modules/@microsoft.azure/autorest-core/resources/plugin-validators.md'
   Including configuration file 'file:///C:/Users/markcowl/.autorest/@microsoft.azure_autorest-core@3.0.5525/node_modules/@microsoft.azure/autorest-core/resources/graphs.md'
   Including configuration file 'file:///C:/Users/markcowl/.autorest/@microsoft.azure_autorest-core@3.0.5525/node_modules/@microsoft.azure/autorest-core/resources/help-configuration.md'
   Loading AutoRest extension '@microsoft.azure/autorest.powershell' (beta->2.0.576)
   Loading AutoRest extension '@microsoft.azure/autorest.remodeler' (beta->2.0.326)
   Loading AutoRest extension '@microsoft.azure/autorest.csharp-v2' (beta->2.0.367)
DEBUG [17.21 s]: swagger-document/loader-swagger - START inputs = 0
DEBUG [17.21 s]: openapi-document-override/md-override-loader-openapi - START inputs = 0
DEBUG [17.22 s]: openapi-document/loader-openapi - START inputs = 0
DEBUG [17.22 s]: swagger-document-override/md-override-loader-swagger - START inputs = 0
DEBUG [17.23 s]: pipeline-emitter - START inputs = 0
DEBUG [17.29 s]: configuration-emitter - START inputs = 0
DEBUG [17.51 s]: pipeline-emitter - END [0.3 s]
DEBUG [17.52 s]: configuration-emitter - END [0.31 s]
DEBUG [21.97 s]: openapi-document/loader-openapi - END [4.76 s]
DEBUG [21.97 s]: openapi-document/individual/transform - SKIPPING
DEBUG [21.97 s]: openapi-document/individual/schema-validator-openapi - SKIPPING
DEBUG [21.98 s]: openapi-document/individual/identity - SKIPPING
DEBUG [21.98 s]: openapi-document-override/md-override-loader-openapi - END [4.77 s]
DEBUG [21.98 s]: swagger-document-override/md-override-loader-swagger - END [4.77 s]
DEBUG [21.98 s]: openapi-document/transform-immediate - SKIPPING
DEBUG [23.45 s]: swagger-document/loader-swagger - END [6.24 s]
DEBUG [23.45 s]: swagger-document/individual/transform - START inputs = 19
DEBUG [23.53 s]: swagger-document/individual/transform - END [0.07 s]
DEBUG [23.53 s]: swagger-document/individual/schema-validator-swagger - START inputs = 19
DEBUG [24.11 s]: swagger-document/individual/schema-validator-swagger - END [0.57 s]
DEBUG [24.11 s]: swagger-document/identity - START inputs = 19
DEBUG [24.11 s]: swagger-document/individual/identity - START inputs = 19
DEBUG [24.12 s]: swagger-document/identity - END [0 s]
DEBUG [24.12 s]: swagger-document/individual/identity - END [0 s]
DEBUG [24.12 s]: openapi-document/openapi-document-converter - START inputs = 19
DEBUG [25.11 s]: openapi-document/openapi-document-converter - END [0.98 s]
DEBUG [25.11 s]: openapi-document/transform - START inputs = 19
DEBUG [25.2 s]: openapi-document/transform - END [0.08 s]
DEBUG [25.2 s]: openapi-document/tree-shaker - START inputs = 19
DEBUG [26.55 s]: openapi-document/tree-shaker - END [1.35 s]
DEBUG [26.56 s]: openapi-document/multi-api-merger - START inputs = 19
DEBUG [32.21 s]: openapi-document/multi-api-merger - END [5.65 s]
DEBUG [32.22 s]: openapi-document/components-cleaner - START inputs = 1
DEBUG [35.28 s]: openapi-document/components-cleaner - END [3.06 s]
DEBUG [35.29 s]: openapi-document/component-modifiers - START inputs = 1
DEBUG [35.29 s]: openapi-document/component-modifiers - END [0 s]
DEBUG [35.29 s]: openapi-document/api-version-parameter-handler - START inputs = 1
DEBUG [35.29 s]: openapi-document/api-version-parameter-handler - END [0 s]
DEBUG [35.29 s]: openapi-document/profile-filter - START inputs = 1
DEBUG [43.13 s]: openapi-document/profile-filter - END [7.83 s]
DEBUG [43.14 s]: openapi-document/model-deduplicator - START inputs = 1
DEBUG [43.14 s]: openapi-document/emitter - START inputs = 1
DEBUG [104.61 s]: openapi-document/emitter - END [61.47 s]
DEBUG [104.61 s]: openapi-document/model-deduplicator - END [61.47 s]
DEBUG [104.62 s]: openapi-document/enum-deduplicator - START inputs = 1
DEBUG [105.12 s]: openapi-document/enum-deduplicator - END [0.5 s]
DEBUG [105.12 s]: openapi-document/subset-reducer - START inputs = 1
C:\Users\markcowl\.autorest\@microsoft.azure_autorest-core@3.0.5525\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js - FAILURE {}
Process() cancelled due to exception : Cannot convert undefined or null to object / TypeError: Cannot convert undefined or null to object
    at Function.getOwnPropertyNames (<anonymous>)
    at SubsetSchemaDeduplicator.visitSchemas (C:\Users\markcowl\.autorest\@microsoft.azure_autorest-core@3.0.5525\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\subset-schemas-deduplicator.js:76:53)
    at SubsetSchemaDeduplicator.visitComponents (C:\Users\markcowl\.autorest\@microsoft.azure_autorest-core@3.0.5525\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\subset-schemas-deduplicator.js:29:26)
    at SubsetSchemaDeduplicator.process (C:\Users\markcowl\.autorest\@microsoft.azure_autorest-core@3.0.5525\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\subset-schemas-deduplicator.js:13:26)
    at SubsetSchemaDeduplicator.runProcess (/node_modules/@microsoft.azure/datastore/dist/processor.js:76:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  TypeError: Cannot convert undefined or null to object
[105.31 s] Shutting Down.
[105.32 s] Exiting.
```

**Comment by MiYanni** [comment]
Fixed: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=68853&view=results
