### ISSUE TITLE
Cannot generate Resources module (Cannot convert undefined or null object)

### ISSUE THREAD

**Issue by markcowl** [Azure/autorest.powershell#417]
Thius is for the resources module here: https://github.com/Azure/azure-powershell/blob/generation/src/Resources/readme.md

Generation produces the following error:
```
PS C:\git\azure-powershell\src\Resources> autorest
AutoRest code generation utility [version: 3.0.5226; node: v10.16.0, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\markcowl\.autorest\@microsoft.azure_autorest-core@3.0.5525\node_modules\@microsoft.azure\autorest-core\dist' (3.0.5525)
   Loading AutoRest extension '@microsoft.azure/autorest.powershell' (beta->2.0.576)
   Loading AutoRest extension '@microsoft.azure/autorest.remodeler' (beta->2.0.326)
   Loading AutoRest extension '@microsoft.azure/autorest.csharp-v2' (beta->2.0.367)
C:\Users\markcowl\.autorest\@microsoft.azure_autorest-core@3.0.5525\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js - FAILURE {}
Process() cancelled due to exception : Cannot convert undefined or null to object / TypeError: Cannot convert undefined or null to object
    at Function.getOwnPropertyNames (<anonymous>)
    at SubsetSchemaDeduplicator.visitSchemas (C:\Users\markcowl\.autorest\@microsoft.azure_autorest-core@3.0.5525\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\subset-schemas-deduplicator.js:76:53)
    at SubsetSchemaDeduplicator.visitComponents (C:\Users\markcowl\.autorest\@microsoft.azure_autorest-core@3.0.5525\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\subset-schemas-deduplicator.js:29:26)
    at SubsetSchemaDeduplicator.process (C:\Users\markcowl\.autorest\@microsoft.azure_autorest-core@3.0.5525\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\subset-schemas-deduplicator.js:13:26)
    at SubsetSchemaDeduplicator.runProcess (/node_modules/@microsoft.azure/datastore/dist/processor.js:76:28)
  TypeError: Cannot convert undefined or null to object
```

**Comment by markcowl** [comment]
Detailed Debug/Verbose logs:
```
PS C:\git\azure-powershell\src\Resources> autorest --debug --verbose
AutoRest code generation utility [version: 3.0.5226; node: v10.16.0, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Network Enabled: true
Starting @microsoft.azure/autorest-core from C:\Users\markcowl\.autorest\@microsoft.azure_autorest-core@3.0.5525
   Loading AutoRest core      'C:\Users\markcowl\.autorest\@microsoft.azure_autorest-core@3.0.5525\node_modules\@microsoft.azure\autorest-core\dist' (3.0.5525)
   Including configuration file 'file:///C:/git/azure-powershell/src/Resources/../readme.azure.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/resources/resource-manager/readme.enable-multi-api.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/resources/resource-manager/readme.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/graphrbac/data-plane/readme.enable-multi-api.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/graphrbac/data-plane/readme.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/managementgroups/resource-manager/readme.enable-multi-api.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/managementgroups/resource-manager/readme.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/authorization/resource-manager/readme.enable-multi-api.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/authorization/resource-manager/readme.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/profiles/readme.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/resources/resource-manager/../../../profiles/readme.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/graphrbac/data-plane/../../../profiles/readme.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/managementgroups/resource-manager/../../../profiles/readme.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/authorization/resource-manager/../../../profiles/readme.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/profiles/definitions/hybrid-2018-03-01.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/profiles/definitions/hybrid-2019-03-01.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/profiles/definitions/latest-2019-04-01.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/profiles/definitions/latest-2019-04-24.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/profiles/definitions/latest-2019-04-29.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/profiles/definitions/latest-2019-04-30.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/profiles/definitions/profile-2017-03-09.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/profiles/definitions/stable-2019-01.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/resources/resource-manager/../../../profiles/definitions/hybrid-2018-03-01.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/resources/resource-manager/../../../profiles/definitions/hybrid-2019-03-01.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/resources/resource-manager/../../../profiles/definitions/latest-2019-04-01.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/resources/resource-manager/../../../profiles/definitions/latest-2019-04-24.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/resources/resource-manager/../../../profiles/definitions/latest-2019-04-29.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/resources/resource-manager/../../../profiles/definitions/latest-2019-04-30.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/resources/resource-manager/../../../profiles/definitions/profile-2017-03-09.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/resources/resource-manager/../../../profiles/definitions/stable-2019-01.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/graphrbac/data-plane/../../../profiles/definitions/hybrid-2018-03-01.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/graphrbac/data-plane/../../../profiles/definitions/hybrid-2019-03-01.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/graphrbac/data-plane/../../../profiles/definitions/latest-2019-04-01.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/graphrbac/data-plane/../../../profiles/definitions/latest-2019-04-24.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/graphrbac/data-plane/../../../profiles/definitions/latest-2019-04-29.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/graphrbac/data-plane/../../../profiles/definitions/latest-2019-04-30.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/graphrbac/data-plane/../../../profiles/definitions/profile-2017-03-09.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/graphrbac/data-plane/../../../profiles/definitions/stable-2019-01.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/managementgroups/resource-manager/../../../profiles/definitions/hybrid-2018-03-01.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/managementgroups/resource-manager/../../../profiles/definitions/hybrid-2019-03-01.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/managementgroups/resource-manager/../../../profiles/definitions/latest-2019-04-01.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/managementgroups/resource-manager/../../../profiles/definitions/latest-2019-04-24.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/managementgroups/resource-manager/../../../profiles/definitions/latest-2019-04-29.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/managementgroups/resource-manager/../../../profiles/definitions/latest-2019-04-30.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/managementgroups/resource-manager/../../../profiles/definitions/profile-2017-03-09.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/managementgroups/resource-manager/../../../profiles/definitions/stable-2019-01.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/authorization/resource-manager/../../../profiles/definitions/hybrid-2018-03-01.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/authorization/resource-manager/../../../profiles/definitions/hybrid-2019-03-01.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/authorization/resource-manager/../../../profiles/definitions/latest-2019-04-01.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/authorization/resource-manager/../../../profiles/definitions/latest-2019-04-24.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/authorization/resource-manager/../../../profiles/definitions/latest-2019-04-29.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/authorization/resource-manager/../../../profiles/definitions/latest-2019-04-30.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/authorization/resource-manager/../../../profiles/definitions/profile-2017-03-09.md'
   Including configuration file 'https://github.com/Azure/azure-rest-api-specs/blob/multiapi/specification/authorization/resource-manager/../../../profiles/definitions/stable-2019-01.md'
   Including configuration file 'file:///C:/Users/markcowl/.autorest/@microsoft.azure_autorest-core@3.0.5525/node_modules/@microsoft.azure/autorest-core/resources/directives.md'
   Including configuration file 'file:///C:/Users/markcowl/.autorest/@microsoft.azure_autorest-core@3.0.5525/node_modules/@microsoft.azure/autorest-core/resources/pipeline-merger.md'
   Including configuration file 'file:///C:/Users/markcowl/.autorest/@microsoft.azure_autorest-core@3.0.5525/node_modules/@microsoft.azure/autorest-core/resources/pipeline-composer.md'
   Including configuration file 'file:///C:/Users/markcowl/.autorest/@microsoft.azure_autorest-core@3.0.5525/node_modules/@microsoft.azure/autorest-core/resources/pipeline-tree-shaker.md'
   Including configuration file 'file:///C:/Users/markcowl/.autorest/@microsoft.azure_autorest-core@3.0.5525/node_modules/@microsoft.azure/autorest-core/resources/loader-openapi2.md'
   Including configuration file 'file:///C:/Users/markcowl/.autorest/@microsoft.azure_autorest-core@3.0.5525/node_modules/@microsoft.azure/autorest-core/resources/loader-openapi3.md'
   Including configuration file 'file:///C:/Users/markcowl/.autorest/@microsoft.azure_autorest-core@3.0.5525/node_modules/@microsoft.azure/autorest-core/resources/markdown-documentation.md'
   Including configuration file 'file:///C:/Users/markcowl/.autorest/@microsoft.azure_autorest-core@3.0.5525/node_modules/@microsoft.azure/autorest-core/resources/miscellaneous.md'
   Including configuration file 'file:///C:/Users/markcowl/.autorest/@microsoft.azure_autorest-core@3.0.5525/node_modules/@microsoft.azure/autorest-core/resources/patches.md'
   Including configuration file 'file:///C:/Users/markcowl/.autorest/@microsoft.azure_autorest-core@3.0.5525/node_modules/@microsoft.azure/autorest-core/resources/plugin-powershell.md'
   Including configuration file 'file:///C:/Users/markcowl/.autorest/@microsoft.azure_autorest-core@3.0.5525/node_modules/@microsoft.azure/autorest-core/resources/plugin-azureresourceschema.md'
   Including configuration file 'file:///C:/Users/markcowl/.autorest/@microsoft.azure_autorest-core@3.0.5525/node_modules/@microsoft.azure/autorest-core/resources/plugin-csharp.md'
   Including configuration file 'file:///C:/Users/markcowl/.autorest/@microsoft.azure_autorest-core@3.0.5525/node_modules/@microsoft.azure/autorest-core/resources/plugin-go.md'
   Including configuration file 'file:///C:/Users/markcowl/.autorest/@microsoft.azure_autorest-core@3.0.5525/node_modules/@microsoft.azure/autorest-core/resources/plugin-java.md'
   Including configuration file 'file:///C:/Users/markcowl/.autorest/@microsoft.azure_autorest-core@3.0.5525/node_modules/@microsoft.azure/autorest-core/resources/plugin-nodejs.md'
   Including configuration file 'file:///C:/Users/markcowl/.autorest/@microsoft.azure_autorest-core@3.0.5525/node_modules/@microsoft.azure/autorest-core/resources/plugin-php.md'
   Including configuration file 'file:///C:/Users/markcowl/.autorest/@microsoft.azure_autorest-core@3.0.5525/node_modules/@microsoft.azure/autorest-core/resources/plugin-python.md'
   Including configuration file 'file:///C:/Users/markcowl/.autorest/@microsoft.azure_autorest-core@3.0.5525/node_modules/@microsoft.azure/autorest-core/resources/plugin-ruby.md'
   Including configuration file 'file:///C:/Users/markcowl/.autorest/@microsoft.azure_autorest-core@3.0.5525/node_modules/@microsoft.azure/autorest-core/resources/plugin-typescript.md'
   Including configuration file 'file:///C:/Users/markcowl/.autorest/@microsoft.azure_autorest-core@3.0.5525/node_modules/@microsoft.azure/autorest-core/resources/plugin-validators.md'
   Including configuration file 'file:///C:/Users/markcowl/.autorest/@microsoft.azure_autorest-core@3.0.5525/node_modules/@microsoft.azure/autorest-core/resources/graphs.md'
   Including configuration file 'file:///C:/Users/markcowl/.autorest/@microsoft.azure_autorest-core@3.0.5525/node_modules/@microsoft.azure/autorest-core/resources/help-configuration.md'
   Loading AutoRest extension '@microsoft.azure/autorest.powershell' (beta->2.0.576)
   Loading AutoRest extension '@microsoft.azure/autorest.remodeler' (beta->2.0.326)
   Loading AutoRest extension '@microsoft.azure/autorest.csharp-v2' (beta->2.0.367)
DEBUG [36.82 s]: swagger-document/loader-swagger - START inputs = 0
DEBUG [36.83 s]: openapi-document-override/md-override-loader-openapi - START inputs = 0
DEBUG [36.83 s]: openapi-document/loader-openapi - START inputs = 0
DEBUG [36.83 s]: swagger-document-override/md-override-loader-swagger - START inputs = 0
DEBUG [36.84 s]: pipeline-emitter - START inputs = 0
DEBUG [36.87 s]: configuration-emitter - START inputs = 0
DEBUG [37 s]: pipeline-emitter - END [0.17 s]
DEBUG [37 s]: configuration-emitter - END [0.17 s]
DEBUG [50.73 s]: openapi-document/loader-openapi - END [13.9 s]
DEBUG [50.73 s]: openapi-document/individual/transform - SKIPPING
DEBUG [50.74 s]: openapi-document/individual/schema-validator-openapi - SKIPPING
DEBUG [50.74 s]: openapi-document/individual/identity - SKIPPING
DEBUG [50.74 s]: openapi-document-override/md-override-loader-openapi - END [13.92 s]
DEBUG [50.74 s]: swagger-document-override/md-override-loader-swagger - END [13.92 s]
DEBUG [50.75 s]: openapi-document/transform-immediate - SKIPPING
DEBUG [51.67 s]: swagger-document/loader-swagger - END [14.84 s]
DEBUG [51.67 s]: swagger-document/individual/transform - START inputs = 45
DEBUG [59.69 s]: swagger-document/individual/transform - END [8.01 s]
DEBUG [59.69 s]: swagger-document/individual/schema-validator-swagger - START inputs = 45
DEBUG [60.16 s]: swagger-document/individual/schema-validator-swagger - END [0.47 s]
DEBUG [60.16 s]: swagger-document/identity - START inputs = 45
DEBUG [60.17 s]: swagger-document/individual/identity - START inputs = 45
DEBUG [60.17 s]: swagger-document/identity - END [0 s]
DEBUG [60.17 s]: swagger-document/individual/identity - END [0 s]
DEBUG [60.17 s]: openapi-document/openapi-document-converter - START inputs = 45
DEBUG [60.81 s]: openapi-document/openapi-document-converter - END [0.64 s]
DEBUG [60.81 s]: openapi-document/transform - START inputs = 45
DEBUG [70.09 s]: openapi-document/transform - END [9.28 s]
DEBUG [70.1 s]: openapi-document/tree-shaker - START inputs = 45
DEBUG [71.34 s]: openapi-document/tree-shaker - END [1.24 s]
DEBUG [71.35 s]: openapi-document/multi-api-merger - START inputs = 45
DEBUG [81.93 s]: openapi-document/multi-api-merger - END [10.58 s]
DEBUG [81.93 s]: openapi-document/components-cleaner - START inputs = 1
DEBUG [85.24 s]: openapi-document/components-cleaner - END [3.3 s]
DEBUG [85.24 s]: openapi-document/component-modifiers - START inputs = 1
DEBUG [85.24 s]: openapi-document/component-modifiers - END [0 s]
DEBUG [85.24 s]: openapi-document/api-version-parameter-handler - START inputs = 1
DEBUG [85.25 s]: openapi-document/api-version-parameter-handler - END [0 s]
DEBUG [85.25 s]: openapi-document/profile-filter - START inputs = 1
DEBUG [90.59 s]: openapi-document/profile-filter - END [5.33 s]
DEBUG [90.59 s]: openapi-document/model-deduplicator - START inputs = 1
DEBUG [90.59 s]: openapi-document/emitter - START inputs = 1
DEBUG [156.77 s]: openapi-document/emitter - END [66.17 s]
DEBUG [156.77 s]: openapi-document/model-deduplicator - END [66.17 s]
DEBUG [156.77 s]: openapi-document/enum-deduplicator - START inputs = 1
DEBUG [157.6 s]: openapi-document/enum-deduplicator - END [0.82 s]
DEBUG [157.6 s]: openapi-document/subset-reducer - START inputs = 1
C:\Users\markcowl\.autorest\@microsoft.azure_autorest-core@3.0.5525\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js - FAILURE {}
Process() cancelled due to exception : Cannot convert undefined or null to object / TypeError: Cannot convert undefined or null to object
    at Function.getOwnPropertyNames (<anonymous>)
    at SubsetSchemaDeduplicator.visitSchemas (C:\Users\markcowl\.autorest\@microsoft.azure_autorest-core@3.0.5525\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\subset-schemas-deduplicator.js:76:53)
    at SubsetSchemaDeduplicator.visitComponents (C:\Users\markcowl\.autorest\@microsoft.azure_autorest-core@3.0.5525\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\subset-schemas-deduplicator.js:29:26)
    at SubsetSchemaDeduplicator.process (C:\Users\markcowl\.autorest\@microsoft.azure_autorest-core@3.0.5525\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\subset-schemas-deduplicator.js:13:26)
    at SubsetSchemaDeduplicator.runProcess (/node_modules/@microsoft.azure/datastore/dist/processor.js:76:28)
  TypeError: Cannot convert undefined or null to object
[157.94 s] Shutting Down.
[157.94 s] Exiting.
```

**Comment by fearthecowboy** [comment]
I get a different error from `export-psd1` -- @MiYanni can look into that

**Comment by MiYanni** [comment]
Original issue is fixed. The other issue related to ArgumentCompleter is something @cormacpayne is aware of where 2 cmdlets get merged that have the same parameter name, but the parameters are of different types. Closing since it is no longer a generator issue.

**Comment by MiYanni** [comment]
I went ahead and fixed this issue in the Resources readme in the Azure PowerShell generation branch.
