### ISSUE TITLE
Resources name (path parameter) with space not being correct handled

### ISSUE THREAD

**Issue by niander** [Azure/autorest.powershell#495]
I have a resource with a name containing spaces. I am trying to run `Update-AzMetricAlert` on it but I am getting the following debug output:

```powershell
$a = Get-AzMetricAlert
Update-AzMetricAlert -ResourceGroupName $a.ResourceGroupName -Name $a.Name -Enabled -Debug
```

```
DEBUG: [CmdletProcessRecordAsyncStart]: Created new QosEvent for command 'Update-AzMetricAlert_UpdateExpanded': AzureQoSEvent: CommandName - Upd
ate-AzMetricAlert_UpdateExpanded; IsSuccess - False; Duration - 00:00:00; Exception - ;
DEBUG: CmdletProcessRecordAsyncStart:
DEBUG: CmdletGetPipeline:
DEBUG: CmdletBeforeAPICall:
DEBUG: URLCreated: https://management.azure.com/subscriptions/<SubscriptionId>/resourceGroups/CSETEST/providers/Microsoft.In
sights/metricAlerts/Percentage CPU greater than 25?api-version=2018-03-01
DEBUG: RequestCreated: https://management.azure.com/subscriptions/<SubscriptionId>/resourceGroups/CSETEST/providers/Microsof
t.Insights/metricAlerts/Percentage CPU greater than 25?api-version=2018-03-01
DEBUG: HeaderParametersAdded: https://management.azure.com/subscriptions/<SubscriptionId>/resourceGroups/CSETEST/providers/M
icrosoft.Insights/metricAlerts/Percentage CPU greater than 25?api-version=2018-03-01
DEBUG: BodyContentSet: https://management.azure.com/subscriptions/<SubscriptionId>/resourceGroups/CSETEST/providers/Microsof
t.Insights/metricAlerts/Percentage CPU greater than 25?api-version=2018-03-01
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PATCH

Absolute Uri:
https://management.azure.com/subscriptions/<SubscriptionId>/resourceGroups/CSETEST/providers/Microsoft.Insights/metricAlerts
/Percentage CPU greater than 25?api-version=2018-03-01

Headers:

Body:
{
  "properties": {
    "enabled": true,
    "evaluationFrequency": "PT0S",
    "severity": 0,
    "windowSize": "PT0S"
  }
}


DEBUG: BeforeCall:
DEBUG: [ADAL]: Information: 2019-08-26T21:40:01.5619513Z: e7c42d17-512a-4522-b909-00ed8014a7a2 - LoggerBase.cs: ADAL PCL.CoreCLR with assembly v
ersion '3.19.2.6005', file version '3.19.50302.0130' and informational version '2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is running...
DEBUG: [ADAL]: Information: 2019-08-26T21:40:01.5620380Z: e7c42d17-512a-4522-b909-00ed8014a7a2 - LoggerBase.cs: ADAL PCL.CoreCLR with assembly v
ersion '3.19.2.6005', file version '3.19.50302.0130' and informational version '2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is running...
DEBUG: [ADAL]: Information: 2019-08-26T21:40:01.5620815Z: e7c42d17-512a-4522-b909-00ed8014a7a2 - LoggerBase.cs: === Token Acquisition started:
        CacheType: null
        Authentication Target: User
        , Authority Host: login.microsoftonline.com
DEBUG: [ADAL]: Information: 2019-08-26T21:40:01.5621162Z: e7c42d17-512a-4522-b909-00ed8014a7a2 - LoggerBase.cs: === Token Acquisition started:
        Authority: https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/
        Resource: https://management.core.windows.net/
        ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
        CacheType: null
        Authentication Target: User

DEBUG: [ADAL]: Verbose: 2019-08-26T21:40:01.5621726Z: e7c42d17-512a-4522-b909-00ed8014a7a2 - LoggerBase.cs: Loading from cache.
DEBUG: [ADAL]: Verbose: 2019-08-26T21:40:01.5622051Z: e7c42d17-512a-4522-b909-00ed8014a7a2 - LoggerBase.cs: Loading from cache.
DEBUG: [ADAL]: Information: 2019-08-26T21:40:01.5685249Z: 00000000-0000-0000-0000-000000000000 - LoggerBase.cs: Deserialized 6 items to token ca
che.
DEBUG: [ADAL]: Verbose: 2019-08-26T21:40:01.5686206Z: e7c42d17-512a-4522-b909-00ed8014a7a2 - LoggerBase.cs: Looking up cache for a token...
DEBUG: [ADAL]: Verbose: 2019-08-26T21:40:01.5686551Z: e7c42d17-512a-4522-b909-00ed8014a7a2 - LoggerBase.cs: Looking up cache for a token...
DEBUG: [ADAL]: Information: 2019-08-26T21:40:01.5687071Z: e7c42d17-512a-4522-b909-00ed8014a7a2 - LoggerBase.cs: An item matching the requested r
esource was found in the cache
DEBUG: [ADAL]: Information: 2019-08-26T21:40:01.5687398Z: e7c42d17-512a-4522-b909-00ed8014a7a2 - LoggerBase.cs: An item matching the requested r
esource was found in the cache
DEBUG: [ADAL]: Information: 2019-08-26T21:40:01.5687831Z: e7c42d17-512a-4522-b909-00ed8014a7a2 - LoggerBase.cs: 18.733037015 minutes left until
token in cache expires
DEBUG: [ADAL]: Information: 2019-08-26T21:40:01.5688149Z: e7c42d17-512a-4522-b909-00ed8014a7a2 - LoggerBase.cs: 18.733037015 minutes left until
token in cache expires
DEBUG: [ADAL]: Information: 2019-08-26T21:40:01.5688455Z: e7c42d17-512a-4522-b909-00ed8014a7a2 - LoggerBase.cs: A matching item (access token or
 refresh token or both) was found in the cache
DEBUG: [ADAL]: Information: 2019-08-26T21:40:01.5688766Z: e7c42d17-512a-4522-b909-00ed8014a7a2 - LoggerBase.cs: A matching item (access token or
 refresh token or both) was found in the cache
DEBUG: [ADAL]: Information: 2019-08-26T21:40:01.5689672Z: e7c42d17-512a-4522-b909-00ed8014a7a2 - LoggerBase.cs: === Token Acquisition finished s
uccessfully. An access token was returned: Expiration Time: 8/26/2019 9:58:45 PM +00:00
DEBUG: [ADAL]: Information: 2019-08-26T21:40:01.5690011Z: e7c42d17-512a-4522-b909-00ed8014a7a2 - LoggerBase.cs: === Token Acquisition finished s
uccessfully. An access token was returned: Expiration Time: 8/26/2019 9:58:45 PM +00:00Access Token Hash: ZeMeL0H4eoWWulcU5KN9slzGIKEBMlkgFsNEE/
UpTGs=
         User id: 9f890239-e15d-4811-9bf7-3e077afb1688
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NotFound

Headers:
Cache-Control                 : private
Server                        : Microsoft-IIS/10.0
X-Powered-By                  : ASP.NET
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-request-id               : 94149ca9-f73a-4b23-bc83-72c718405d1f
x-ms-correlation-request-id   : 94149ca9-f73a-4b23-bc83-72c718405d1f
x-ms-routing-request-id       : WESTUS:20190826T214002Z:94149ca9-f73a-4b23-bc83-72c718405d1f
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Date                          : Mon, 26 Aug 2019 21:40:01 GMT

Body:
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>IIS 10.0 Detailed Error - 404.4 - Not Found</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana,Arial,Helvetica,sans-serif;}
code{margin:0;color:#006600;font-size:1.1em;font-weight:bold;}
.config_source code{font-size:.8em;color:#000000;}
pre{margin:0;font-size:1.4em;word-wrap:break-word;}
ul,ol{margin:10px 0 10px 5px;}
ul.first,ol.first{margin-top:5px;}
fieldset{padding:0 15px 10px 15px;word-break:break-all;}
.summary-container fieldset{padding-bottom:5px;margin-top:4px;}
legend.no-expand-all{padding:2px 15px 4px 10px;margin:0 0 0 -12px;}
legend{color:#333333;;margin:4px 0 8px -12px;_margin-top:0px;
font-weight:bold;font-size:1em;}
a:link,a:visited{color:#007EFF;font-weight:bold;}
a:hover{text-decoration:none;}
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;}
h3{font-size:1.4em;margin:10px 0 0 0;color:#CC0000;}
h4{font-size:1.2em;margin:10px 0 5px 0;
}#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS",Verdana,sans-serif;
 color:#FFF;background-color:#5C87B2;
}#content{margin:0 0 0 2%;position:relative;}
.summary-container,.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
.content-container p{margin:0 0 10px 0;
}#details-left{width:35%;float:left;margin-right:2%;
}#details-right{width:63%;float:left;overflow:hidden;
}#server_version{width:96%;_height:1px;min-height:1px;margin:0 0 5px 0;padding:11px 2% 8px 2%;color:#FFFFFF;
 background-color:#5A7FA5;border-bottom:1px solid #C1CFDD;border-top:1px solid #4A6C8E;font-weight:normal;
 font-size:1em;color:#FFF;text-align:right;
}#server_version p{margin:5px 0;}
table{margin:4px 0 4px 0;width:100%;border:none;}
td,th{vertical-align:top;padding:3px 0;text-align:left;font-weight:normal;border:none;}
th{width:30%;text-align:right;padding-right:2%;font-weight:bold;}
thead th{background-color:#ebebeb;width:25%;
}#details-right th{width:20%;}
table tr.alt td,table tr.alt th{}
.highlight-code{color:#CC0000;font-weight:bold;font-style:italic;}
.clear{clear:both;}
.preferred{padding:0 5px 2px 5px;font-weight:normal;background:#006633;color:#FFF;font-size:.8em;}
-->
</style>

</head>
<body>
<div id="content">
<div class="content-container">
  <h3>HTTP Error 404.4 - Not Found</h3>
  <h4>The resource you are looking for does not have a handler associated with it.</h4>
</div>
<div class="content-container">
 <fieldset><h4>Most likely causes:</h4>
  <ul>  <li>The file extension for the requested URL does not have a handler configured to process the request on the Web server.</li> </ul>
 </fieldset>
</div>
<div class="content-container">
 <fieldset><h4>Things you can try:</h4>
  <ul>  <li>If the file extension does not have a handler associated with it, add a handler mapping for the extension.</li>     <li>Verify that
the handler associated with the file extension is properly installed and configured.</li>       <li>Create a tracing rule to track failed reques
ts for this HTTP status code. For more information about creating a tracing rule for failed requests, click <a href="http://go.microsoft.com/fwl
ink/?LinkID=66439">here</a>. </li> </ul>
 </fieldset>
</div>

<div class="content-container">
 <fieldset><h4>Detailed Error Information:</h4>
  <div id="details-left">
   <table border="0" cellpadding="0" cellspacing="0">
    <tr class="alt"><th>Module</th><td>&nbsp;&nbsp;&nbsp;IIS Web Core</td></tr>
    <tr><th>Notification</th><td>&nbsp;&nbsp;&nbsp;MapRequestHandler</td></tr>
    <tr class="alt"><th>Handler</th><td>&nbsp;&nbsp;&nbsp;Not yet determined</td></tr>
    <tr><th>Error Code</th><td>&nbsp;&nbsp;&nbsp;0x80070002</td></tr>

   </table>
  </div>
  <div id="details-right">
   <table border="0" cellpadding="0" cellspacing="0">
    <tr class="alt"><th>Requested URL</th><td>&nbsp;&nbsp;&nbsp;https://genevaalertrpprod.monitoring.windows.net:443/subscriptions/9e223dbe-3399
-4e19-88eb-0975f02ac87f/resourceGroups/CSETEST/providers/Microsoft.Insights/metricAlerts/Percentage CPU greater than 25?api-version=2018-03-01</
td></tr>
    <tr><th>Physical Path</th><td>&nbsp;&nbsp;&nbsp;E:\sitesroot\0\subscriptions\<SubscriptionId>\resourceGroups\CSETEST\pro
viders\Microsoft.Insights\metricAlerts\Percentage CPU greater than 25</td></tr>
    <tr class="alt"><th>Logon Method</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr>
    <tr><th>Logon User</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr>
    <tr class="alt"><th>Request Tracing Directory</th><td>&nbsp;&nbsp;&nbsp;C:\Resources\directory\5bdbf4b084284f3aba7fad616b82d02f.AlertRpWebAp
i.DiagnosticStore\FailedReqLogFiles\Web</td></tr>
   </table>
   <div class="clear"></div>
  </div>
 </fieldset>
</div>

<div class="content-container">
 <fieldset><h4>More Information:</h4>
  This error means that the Web server does not recognize the file extension of the requested resource. A module handler is not configured on th
e Web server for this extension. If the file extension being denied is required by the Web server, add the appropriate handler for the file exte
nsion.
  <p><a href="http://go.microsoft.com/fwlink/?LinkID=62293&amp;IIS70Error=404,4,0x80070002,14393">View more information &raquo;</a></p>

 </fieldset>
</div>
</div>
</body>
</html>



DEBUG: ResponseCreated:
DEBUG: BeforeResponseDispatch:
DEBUG: Finally:
DEBUG: [CmdletProcessRecordAsyncEnd]: Sending new QosEvent for command 'Update-AzMetricAlert_UpdateExpanded': AzureQoSEvent: CommandName - Updat
e-AzMetricAlert_UpdateExpanded; IsSuccess - True; Duration - 00:00:00; Exception - ;
DEBUG: CmdletProcessRecordAsyncEnd:
DEBUG: [CmdletException]: Received Exception with message 'ParserException - Expected literal (number, boolean, or null). Was '<'. :    at Micro
soft.Azure.PowerShell.Cmdlets.Monitor.Runtime.Json.JsonTokenizer.ReadIdentifer() in C:\Users\niassis\source\repos\generating\azure-powershell\sr
c\Monitor\generated\runtime\Parser\JsonTokenizer.cs:line 115
   at Microsoft.Azure.PowerShell.Cmdlets.Monitor.Runtime.Json.JsonTokenizer.ReadLiteral() in C:\Users\niassis\source\repos\generating\azure-powe
rshell\src\Monitor\generated\runtime\Parser\JsonTokenizer.cs:line 85
   at Microsoft.Azure.PowerShell.Cmdlets.Monitor.Runtime.Json.JsonTokenizer.ReadNext() in C:\Users\niassis\source\repos\generating\azure-powersh
ell\src\Monitor\generated\runtime\Parser\JsonTokenizer.cs:line 44
   at Microsoft.Azure.PowerShell.Cmdlets.Monitor.Runtime.Json.TokenReader.Next() in C:\Users\niassis\source\repos\generating\azure-powershell\sr
c\Monitor\generated\runtime\Parser\TokenReader.cs:line 17
   at Microsoft.Azure.PowerShell.Cmdlets.Monitor.Runtime.Json.JsonParser..ctor(SourceReader sourceReader) in C:\Users\niassis\source\repos\gener
ating\azure-powershell\src\Monitor\generated\runtime\Parser\JsonParser.cs:line 21
   at Microsoft.Azure.PowerShell.Cmdlets.Monitor.Runtime.Json.JsonNode.Parse(SourceReader sourceReader) in C:\Users\niassis\source\repos\generat
ing\azure-powershell\src\Monitor\generated\runtime\Nodes\JsonNode.cs:line 81
   at Microsoft.Azure.PowerShell.Cmdlets.Monitor.Runtime.Json.JsonNode.Parse(String text) in C:\Users\niassis\source\repos\generating\azure-powe
rshell\src\Monitor\generated\runtime\Nodes\JsonNode.cs:line 73
   at Microsoft.Azure.PowerShell.Cmdlets.Monitor.Monitor.<>c.<MetricAlertsUpdate_Call>b__194_1(Task`1 body) in C:\Users\niassis\source\repos\gen
erating\azure-powershell\src\Monitor\generated\api\Monitor.cs:line 8113
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.PowerShell.Cmdlets.Monitor.Cmdlets.UpdateAzMetricAlert_UpdateExpanded.onDefault(HttpResponseMessage responseMessage, Task`
1 response) in C:\Users\niassis\source\repos\generating\azure-powershell\src\Monitor\generated\cmdlets\UpdateAzMetricAlert_UpdateExpanded.cs:lin
e 499
   at Microsoft.Azure.PowerShell.Cmdlets.Monitor.Monitor.MetricAlertsUpdate_Call(HttpRequestMessage request, Func`3 onOk, Func`3 onDefault, IEve
ntListener eventListener, ISendAsync sender) in C:\Users\niassis\source\repos\generating\azure-powershell\src\Monitor\generated\api\Monitor.cs:l
ine 8113
   at Microsoft.Azure.PowerShell.Cmdlets.Monitor.Monitor.MetricAlertsUpdate_Call(HttpRequestMessage request, Func`3 onOk, Func`3 onDefault, IEve
ntListener eventListener, ISendAsync sender) in C:\Users\niassis\source\repos\generating\azure-powershell\src\Monitor\generated\api\Monitor.cs:l
ine 8124
   at Microsoft.Azure.PowerShell.Cmdlets.Monitor.Monitor.MetricAlertsUpdate(String subscriptionId, String resourceGroupName, String ruleName, IM
etricAlertResourcePatch body, Func`3 onOk, Func`3 onDefault, IEventListener eventListener, ISendAsync sender) in C:\Users\niassis\source\repos\g
enerating\azure-powershell\src\Monitor\generated\api\Monitor.cs:line 8019
   at Microsoft.Azure.PowerShell.Cmdlets.Monitor.Cmdlets.UpdateAzMetricAlert_UpdateExpanded.ProcessRecordAsync() in C:\Users\niassis\source\repo
s\generating\azure-powershell\src\Monitor\generated\cmdlets\UpdateAzMetricAlert_UpdateExpanded.cs:line 449
   at Microsoft.Azure.PowerShell.Cmdlets.Monitor.Cmdlets.UpdateAzMetricAlert_UpdateExpanded.ProcessRecordAsync() in C:\Users\niassis\source\repo
s\generating\azure-powershell\src\Monitor\generated\cmdlets\UpdateAzMetricAlert_UpdateExpanded.cs:line 459'
DEBUG: CmdletException: ParserException - Expected literal (number, boolean, or null). Was '<'. :    at Microsoft.Azure.PowerShell.Cmdlets.Monit
or.Runtime.Json.JsonTokenizer.ReadIdentifer() in C:\Users\niassis\source\repos\generating\azure-powershell\src\Monitor\generated\runtime\Parser\
JsonTokenizer.cs:line 115
   at Microsoft.Azure.PowerShell.Cmdlets.Monitor.Runtime.Json.JsonTokenizer.ReadLiteral() in C:\Users\niassis\source\repos\generating\azure-powe
rshell\src\Monitor\generated\runtime\Parser\JsonTokenizer.cs:line 85
   at Microsoft.Azure.PowerShell.Cmdlets.Monitor.Runtime.Json.JsonTokenizer.ReadNext() in C:\Users\niassis\source\repos\generating\azure-powersh
ell\src\Monitor\generated\runtime\Parser\JsonTokenizer.cs:line 44
   at Microsoft.Azure.PowerShell.Cmdlets.Monitor.Runtime.Json.TokenReader.Next() in C:\Users\niassis\source\repos\generating\azure-powershell\sr
c\Monitor\generated\runtime\Parser\TokenReader.cs:line 17
   at Microsoft.Azure.PowerShell.Cmdlets.Monitor.Runtime.Json.JsonParser..ctor(SourceReader sourceReader) in C:\Users\niassis\source\repos\gener
ating\azure-powershell\src\Monitor\generated\runtime\Parser\JsonParser.cs:line 21
   at Microsoft.Azure.PowerShell.Cmdlets.Monitor.Runtime.Json.JsonNode.Parse(SourceReader sourceReader) in C:\Users\niassis\source\repos\generat
ing\azure-powershell\src\Monitor\generated\runtime\Nodes\JsonNode.cs:line 81
   at Microsoft.Azure.PowerShell.Cmdlets.Monitor.Runtime.Json.JsonNode.Parse(String text) in C:\Users\niassis\source\repos\generating\azure-powe
rshell\src\Monitor\generated\runtime\Nodes\JsonNode.cs:line 73
   at Microsoft.Azure.PowerShell.Cmdlets.Monitor.Monitor.<>c.<MetricAlertsUpdate_Call>b__194_1(Task`1 body) in C:\Users\niassis\source\repos\gen
erating\azure-powershell\src\Monitor\generated\api\Monitor.cs:line 8113
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.PowerShell.Cmdlets.Monitor.Cmdlets.UpdateAzMetricAlert_UpdateExpanded.onDefault(HttpResponseMessage responseMessage, Task`
1 response) in C:\Users\niassis\source\repos\generating\azure-powershell\src\Monitor\generated\cmdlets\UpdateAzMetricAlert_UpdateExpanded.cs:lin
e 499
   at Microsoft.Azure.PowerShell.Cmdlets.Monitor.Monitor.MetricAlertsUpdate_Call(HttpRequestMessage request, Func`3 onOk, Func`3 onDefault, IEve
ntListener eventListener, ISendAsync sender) in C:\Users\niassis\source\repos\generating\azure-powershell\src\Monitor\generated\api\Monitor.cs:l
ine 8113
   at Microsoft.Azure.PowerShell.Cmdlets.Monitor.Monitor.MetricAlertsUpdate_Call(HttpRequestMessage request, Func`3 onOk, Func`3 onDefault, IEve
ntListener eventListener, ISendAsync sender) in C:\Users\niassis\source\repos\generating\azure-powershell\src\Monitor\generated\api\Monitor.cs:l
ine 8124
   at Microsoft.Azure.PowerShell.Cmdlets.Monitor.Monitor.MetricAlertsUpdate(String subscriptionId, String resourceGroupName, String ruleName, IM
etricAlertResourcePatch body, Func`3 onOk, Func`3 onDefault, IEventListener eventListener, ISendAsync sender) in C:\Users\niassis\source\repos\g
enerating\azure-powershell\src\Monitor\generated\api\Monitor.cs:line 8019
   at Microsoft.Azure.PowerShell.Cmdlets.Monitor.Cmdlets.UpdateAzMetricAlert_UpdateExpanded.ProcessRecordAsync() in C:\Users\niassis\source\repo
s\generating\azure-powershell\src\Monitor\generated\cmdlets\UpdateAzMetricAlert_UpdateExpanded.cs:line 449
   at Microsoft.Azure.PowerShell.Cmdlets.Monitor.Cmdlets.UpdateAzMetricAlert_UpdateExpanded.ProcessRecordAsync() in C:\Users\niassis\source\repo
s\generating\azure-powershell\src\Monitor\generated\cmdlets\UpdateAzMetricAlert_UpdateExpanded.cs:line 459
```

**Comment by niander** [comment]
More investigations and I found out that the problem was not the space but the PATCH operation itself. Closing this now.
