### ISSUE TITLE
Azure Stack: Building module fails with error - The parameter 'x' cannot be specified because it conflicts with the parameter alias of the same name

### ISSUE THREAD

**Issue by rakku-ms** [Azure/autorest.powershell#535]
Commands:
1) autorest-beta
2) pwsh
3) .\build-module.ps1

Location: 
https://github.com/rakku-ms/azure-powershell/tree/user/rakku/autorest/src/StackAdmin/Azs.Storage.Admin

Error:
$MetadataException/   at System.Management.Automation.MergedCommandParameterMetadata.AddMetadataForBinder(InternalParameterMetadata parameterMetadata, ParameterBinderAssociation binderAssociation)
   at System.Management.Automation.CommandMetadata.MergeParameterMetadata(ExecutionContext context, InternalParameterMetadata parameterMetadata, Boolean shouldGenerateCommonParameters)
   at System.Management.Automation.CommandMetadata..ctor(ScriptBlock scriptblock, String commandName, ExecutionContext context)
   at System.Management.Automation.FunctionInfo.get_CommandMetadata()
   at System.Management.Automation.CommandInfo.GenerateCommandParameterSetInfo()
   at System.Management.Automation.CommandInfo.get_ParameterSets()
   at Microsoft.Azure.PowerShell.Cmdlets.StorageAdmin.Runtime.PowerShell.PsProxyTypeExtensions.ToVariants(CommandInfo info, PsHelpInfo helpInfo) in C:\WD\GitHub\Azure\azure-powershell\src\StackAdmin\Azs.Storage.Admin\generated\runtime\BuildTime\Models\PsProxyTypes.cs:line 448
   at Microsoft.Azure.PowerShell.Cmdlets.StorageAdmin.Runtime.PowerShell.PsProxyTypeExtensions.ToVariants(CommandInfo info, PSObject helpInfo) in C:\WD\GitHub\Azure\azure-powershell\src\StackAdmin\Azs.Storage.Admin\generated\runtime\BuildTime\Models\PsProxyTypes.cs:line 456
   at Microsoft.Azure.PowerShell.Cmdlets.StorageAdmin.Runtime.PowerShell.ExportTestStub.<>c.<ProcessRecord>b__16_0(FunctionInfo fi) in C:\WD\GitHub\Azure\azure-powershell\src\StackAdmin\Azs.Storage.Admin\generated\runtime\BuildTime\Cmdlets\ExportTestStub.cs:line 55
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Lookup`2.Create(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`2.GetEnumerator()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at Microsoft.Azure.PowerShell.Cmdlets.StorageAdmin.Runtime.PowerShell.ExportTestStub.ProcessRecord() in C:\WD\GitHub\Azure\azure-powershell\src\StackAdmin\Azs.Storage.Admin\generated\runtime\BuildTime\Cmdlets\ExportTestStub.cs:line 61
Export-TestStub : The parameter 'FarmId' cannot be specified because it conflicts with the parameter alias of the same name for parameter 'Id'.
At C:\WD\GitHub\Azure\azure-powershell\src\StackAdmin\Azs.Storage.Admin\build-module.ps1:135 char:1
+ Export-TestStub -ModuleName $moduleName -ExportsFolder $exportsFolder ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : MetadataError: (:) [Export-TestStub], MetadataException
+ FullyQualifiedErrorId : ParameterNameConflictsWithAlias,Microsoft.Azure.PowerShell.Cmdlets.StorageAdmin.Runtime.PowerShell.ExportTestStub

**Comment by dolauli** [comment]
It looks like a naming issue, suggest you could either rename the parameter name in the readme.md/directives or in the swagger file to work around issue until we have time to fix it in the generator.

**Comment by bganapa** [comment]
@rakku-ms could you pls close this , i think it got fixed
