### ISSUE TITLE
[Azure Stack] Azs.Gallery.Admin module is unable to build (IndexOutOfRangeException)

### ISSUE THREAD

**Issue by viananth** [Azure/autorest.powershell#575]
Azs.Gallery.Admin module was able to be generated using autorest-beta. But while trying to build it using "build-module", it throws the index out-of-range exception. This error repros in latest autorest-beta.

**Repro steps:**

[Rest-Api-Spec link](https://github.com/Azure/azure-rest-api-specs/tree/stackadmin/specification/azsadmin/resource-manager/gallery)
[Module Readme.md](https://github.com/Azure/azurestack-powershell-pr/blob/dev/src/Azs.Gallery.Admin/readme.md)

**Autorest version:**

`D:\github\azurestack-powershell-pr\src\Azs.Gallery.Admin>autorest-beta --version
openssl config failed: error:02001003:system library:fopen:No such process
AutoRest code generation utility [version: 3.0.6149; node: v10.16.0, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest

Showing All Installed Extensions

 Type       Extension Name                           Version      Location
 core       @autorest/core                           3.0.6130     C:\Users\viananth\.autorest\@autorest_core@3.0.6130
 core       @autorest/core                           3.0.6158     C:\Users\viananth\.autorest\@autorest_core@3.0.6158
 extension  @autorest/powershell                     2.1.329      C:\Users\viananth\.autorest\@autorest_powershell@2.1.329
 extension  @autorest/remodeler                      2.1.23       C:\Users\viananth\.autorest\@autorest_remodeler@2.1.23`

**Powershell:**

D:\github\azurestack-powershell-pr\src\Azs.Gallery.Admin>autorest-beta
openssl config failed: error:02001003:system library:fopen:No such process
AutoRest code generation utility [version: 3.0.6149; node: v10.16.0, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\viananth\.autorest\@autorest_core@3.0.6158\node_modules\@autorest\core\dist' (3.0.6158)
   Loading AutoRest extension '@autorest/powershell' (~2.1.327->2.1.329)
   Loading AutoRest extension '@autorest/remodeler' (~2.1.0->2.1.23)
openssl config failed: error:02001003:system library:fopen:No such process
openssl config failed: error:02001003:system library:fopen:No such process
[9.13 s] Generation Complete

**PowerShell Core:**

PS D:\github\azurestack-powershell-pr\src\Azs.Gallery.Admin> .\build-module.ps1
Creating isolated process...
Cleaning build folders...
Compiling module...
Creating exports and docs...
$IndexOutOfRangeException/   at Microsoft.Azure.PowerShell.Cmdlets.Gallery.Runtime.PowerShell.MarkdownHelpInfo.<>c.<GetExamplesFromMarkdown>b__52_4(String[] eg) in D:\github\azurestack-powershell-pr\src\Azs.Gallery.Admin\generated\runtime\BuildTime\Models\PsMarkdownTypes.cs:line 91
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.Azure.PowerShell.Cmdlets.Gallery.Runtime.PowerShell.MarkdownHelpInfo.GetExamplesFromMarkdown(String examplesFolder) in D:\github\azurestack-powershell-pr\src\Azs.Gallery.Admin\generated\runtime\BuildTime\Models\PsMarkdownTypes.cs:line 82
   at Microsoft.Azure.PowerShell.Cmdlets.Gallery.Runtime.PowerShell.MarkdownHelpInfo..ctor(VariantGroup variantGroup, String examplesFolder, String externalHelpFilename) in D:\github\azurestack-powershell-pr\src\Azs.Gallery.Admin\generated\runtime\BuildTime\Models\PsMarkdownTypes.cs:line 51
   at Microsoft.Azure.PowerShell.Cmdlets.Gallery.Runtime.PowerShell.MarkdownRenderer.<>c__DisplayClass0_0.<WriteMarkdowns>b__1(VariantGroup vg) in D:\github\azurestack-powershell-pr\src\Azs.Gallery.Admin\generated\runtime\BuildTime\MarkdownRenderer.cs:line 16
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.Azure.PowerShell.Cmdlets.Gallery.Runtime.PowerShell.MarkdownRenderer.WriteMarkdowns(IEnumerable`1 variantGroups, PsModuleHelpInfo moduleHelpInfo, String docsFolder, String examplesFolder) in D:\github\azurestack-powershell-pr\src\Azs.Gallery.Admin\generated\runtime\BuildTime\MarkdownRenderer.cs:line 16
   at Microsoft.Azure.PowerShell.Cmdlets.Gallery.Runtime.PowerShell.ExportProxyCmdlet.ProcessRecord() in D:\github\azurestack-powershell-pr\src\Azs.Gallery.Admin\generated\runtime\BuildTime\Cmdlets\ExportProxyCmdlet.cs:line 121
Export-ProxyCmdlet : Index was outside the bounds of the array.
At D:\github\azurestack-powershell-pr\src\Azs.Gallery.Admin\build-module.ps1:121 char:3
+   Export-ProxyCmdlet -ModuleName $moduleName -ModulePath $modulePaths ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Export-ProxyCmdlet], IndexOutOfRangeException
+ FullyQualifiedErrorId : System.IndexOutOfRangeException,Microsoft.Azure.PowerShell.Cmdlets.Gallery.Runtime.PowerShell.ExportProxyCmdlet

**Comment by viananth** [comment]
@bganapa @markcowl

**Comment by viananth** [comment]
It was a bug in examples. Fixed it.
