### ISSUE TITLE
  Error: Plugin csnamer reported failure.

### ISSUE THREAD

**Issue by icyfire0573** [Azure/autorest.powershell#696]
[ManageAPI.zip](https://github.com/Azure/autorest/files/5367080/ManageAPI.zip)

```
C:\Users\WDAGUtilityAccount\Documents>autorest --powershell --input-file=C:\Users\WDAGUtilityAccount\Desktop\ManageAPI.json  --namespace=Connectwise.Manage    --debug

PLUGIN FAILURE: Unknown Model. Fatal., Error: Unknown Model. Fatal.
    at SchemaDefinitionResolver.resolveTypeDeclaration (C:\Users\WDAGUtilityAccount\.autorest\@autorest_powershell@2.1.400\node_modules\@autorest\powershell\llcsharp\schema\schema-resolver.ts:145:11)
    at SchemaDefinitionResolver.resolveTypeDeclaration (C:\Users\WDAGUtilityAccount\.autorest\@autorest_powershell@2.1.400\node_modules\@autorest\powershell\llcsharp\schema\schema-resolver.ts:41:121)
    at SchemaDefinitionResolver.resolveTypeDeclaration (C:\Users\WDAGUtilityAccount\.autorest\@autorest_powershell@2.1.400\node_modules\@autorest\powershell\llcsharp\schema\schema-resolver.ts:41:121)
    at setOperationNames (C:\Users\WDAGUtilityAccount\.autorest\@autorest_powershell@2.1.400\node_modules\@autorest\powershell\plugins\cs-namer.ts:191:67)
    at nameStuffRight (C:\Users\WDAGUtilityAccount\.autorest\@autorest_powershell@2.1.400\node_modules\@autorest\powershell\plugins\cs-namer.ts:234:9)
    at Object.processCodeModel (C:\Users\WDAGUtilityAccount\.autorest\@autorest_powershell@2.1.400\node_modules\@azure-tools\codemodel-v3\process-code-model.ts:16:96)
    at C:\Users\WDAGUtilityAccount\.autorest\@autorest_powershell@2.1.400\node_modules\@azure-tools\autorest-extension-base\extension-base.ts:68:9, {}
FATAL: Error: Unknown Model. Fatal.
C:\Users\WDAGUtilityAccount\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist\lib\pipeline\pipeline.js - FAILURE {}
Process() cancelled due to exception : Plugin csnamer reported failure. / Error: Plugin csnamer reported failure.
    at C:\Users\WDAGUtilityAccount\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist\lib\pipeline\plugins\external.js:26:19
    at async ScheduleNode (C:\Users\WDAGUtilityAccount\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist\lib\pipeline\pipeline.js:294:33)
  Error: Plugin csnamer reported failure.
```

**Comment by isra-fel** [comment]
@icyfire0573  I can't reproduce with latest autorest.powershell extension, could you try it?
`autorest --powershell --use:@autorest/powershell@3.0.403 --input-file=ManageAPI.json --namespace=Connectwise.Manage  --debug`

**Comment by icyfire0573** [comment]
Two things. One; apparently I need a better computer. It takes me an extra 1000 seconds to get to the csnamer :p

DEBUG [1863.08 s]: csnamer-v2 - START inputs = 1
DEBUG [2353.68 s]: csnamer-v2 - END [490.6 s]
DEBUG [2353.69 s]: psnamer-v2 - START inputs = 1
DEBUG [3871.35 s]: psnamer-v2 - END [1517.64 s]
DEBUG [3871.46 s]: modifiers-v2 - START inputs = 1
DEBUG [5487.72 s]: modifiers-v2 - END [1616.25 s]
DEBUG [5487.73 s]: add-azure-completers-v2 - START inputs = 1
DEBUG [5487.73 s]: llcsharp-v2 - START inputs = 1

I can verify that I get past that now (I had to change the command line a little to make it work) 
autorest --powershell --use:@autorest/powershell@3.0.403 --input-file=C:\Users\WDAGUtilityAccount\Desktop\ManageAPI.json  --namespace=Connectwise.Manage    --debug --max-memory-size=8192

However, Now the system seems to be stuck at the llcsharp-v2 its been there for the past 24 hours and hasn't made any progress.

**Comment by isra-fel** [comment]
@icyfire0573 Hi, about the performance, I suggest:

1. Cut the size of your input swagger file - remove unnecessary APIs, or you may split it into multiple smaller files
1. Run it on a more powerful computer

I use a `Intel(R) Xeon(R) W-2123 CPU @ 3.60GHz   3.60 GHz` CPU with 32G memory and it took me ~2 hours to finish generation. Could you share your hardware info BTW?

**Comment by icyfire0573** [comment]
I don't know what happened to the first run, but it never completed (after 2 days). I ran it a second time and it took 4 hours. Looks like this issue has been resolved. Thanks for your time.
