### ISSUE TITLE
[AzureStack] Autorest generated cmdlet throwing "Argument passed in is not serializable" error

### ISSUE THREAD

**Issue by rakku-ms** [Azure/autorest.powershell#755]
This is for AzureStack specific admin modules
Some of the generated cmdlets throw "Argument passed in is not serializable" error when incorrect parameter value is passed. In the below examples, "TargetSubscriptionId" parameter value is correct for the first one but not for the second one.

```
PS C:\Windows\system32> Get-AzsUserSubscription -TargetSubscriptionId "966bbf24-21ce-43bd-8735-e1a4c0eed411"

DelegatedProviderSubscriptionId      DisplayName                  ExternalReferenceId OfferId                                                                           
-------------------------------      -----------                  ------------------- -------                                                                           
209523fa-09a8-4642-93df-58496efe1ca2 EventRPBVTTenantSubscription                     /subscriptions/209523fa-09a8-4642-93df-58496efe1ca2/resourceGroups/EventRPBVTTe...



PS C:\Windows\system32> Get-AzsUserSubscription -TargetSubscriptionId "966bbf24-21ce-43bd-8735-e1a4c0eed418"
Get-AzsUserSubscription : Argument passed in is not serializable.
Parameter name: value
At line:1 char:1
+ Get-AzsUserSubscription -TargetSubscriptionId "966bbf24-21ce-43bd-873 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzsUserSubscription_Get], ArgumentException
    + FullyQualifiedErrorId : Microsoft.Azure.PowerShell.Cmdlets.SubscriptionsAdmin.Cmdlets.GetAzsUserSubscription_Get
```

**Comment by dolauli** [comment]
@rakku-ms Please add '-debug' when running the cmdlet.

**Comment by rakku-ms** [comment]
@dolauli please find the debug log below
```
PS C:\Windows\system32> Get-AzsUserSubscription -TargetSubscriptionId "966bbf24-21ce-43bd-8735-e1a4c0eed418" -debug
DEBUG: 7:28:21 PM - GetAzureRMContextCommand end processing.
DEBUG: [CmdletBeginProcessing]: Starting command
DEBUG: CmdletBeginProcessing: 
DEBUG: CmdletProcessRecordStart: 
DEBUG: [CmdletProcessRecordAsyncStart]: Created new QosEvent for command 'Get-AzsUserSubscription_Get': AzureQoSEvent: CommandName - Get-AzsUserSubscription_Get; IsSucce
ss - False; Duration - 00:00:00
DEBUG: CmdletProcessRecordAsyncStart: 
DEBUG: CmdletGetPipeline: 
DEBUG: CmdletBeforeAPICall: 
DEBUG: URLCreated: /subscriptions/209523fa-09a8-4642-93df-58496efe1ca2/providers/Microsoft.Subscriptions.Admin/subscriptions/966bbf24-21ce-43bd-8735-e1a4c0eed418?api-ver
sion=2015-11-01
DEBUG: RequestCreated: /subscriptions/209523fa-09a8-4642-93df-58496efe1ca2/providers/Microsoft.Subscriptions.Admin/subscriptions/966bbf24-21ce-43bd-8735-e1a4c0eed418?api
-version=2015-11-01
DEBUG: HeaderParametersAdded: 
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://adminmanagement.local.azurestack.external/subscriptions/209523fa-09a8-4642-93df-58496efe1ca2/providers/Microsoft.Subscriptions.Admin/subscriptions/966bbf24-21ce-
43bd-8735-e1a4c0eed418?api-version=2015-11-01

Headers:
x-ms-unique-id                : 103
x-ms-client-request-id        : 6cce09eb-62a3-4885-96e6-a1057453f473
CommandName                   : Get-AzsUserSubscription
FullCommandName               : Get-AzsUserSubscription_Get
ParameterSetName              : __AllParameterSets
User-Agent                    : AzurePowershell/Az4.0.0-preview

Body:



DEBUG: BeforeCall: 
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NotFound

Headers:
Pragma                        : no-cache
x-ms-ratelimit-remaining-subscription-reads: 14926
x-ms-request-id               : 191e9789-ca81-49ef-b35e-283c7ab6cad1
x-ms-correlation-request-id   : 191e9789-ca81-49ef-b35e-283c7ab6cad1
x-ms-routing-request-id       : LOCAL:20210324T022829Z:191e9789-ca81-49ef-b35e-283c7ab6cad1
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Wed, 24 Mar 2021 02:28:29 GMT

Body:
{
  "error": {
    "code": "SubscriptionNotFound",
    "message": "The subscription '966bbf24-21ce-43bd-8735-e1a4c0eed418' could not be found."
  }
}


DEBUG: ResponseCreated: 
DEBUG: [CmdletProcessRecordAsyncEnd]: Finish HTTP process
DEBUG: CmdletProcessRecordAsyncEnd: 
DEBUG: [CmdletException]: Received Exception with message 'ArgumentException - Argument passed in is not serializable.
Parameter name: value :    at System.Collections.ListDictionaryInternal.set_Item(Object key, Object value)
   at Microsoft.Azure.Commands.Common.AzModule.<OnFinally>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Commands.Common.AzModule.<EventListener>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.PowerShell.Cmdlets.SubscriptionsAdmin.Module.<Signal>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.PowerShell.Cmdlets.SubscriptionsAdmin.Cmdlets.GetAzsUserSubscription_Get.<Microsoft-Azure-PowerShell-Cmdlets-SubscriptionsAdmin-Runtime-IEventListe
ner-Signal>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.PowerShell.Cmdlets.SubscriptionsAdmin.SubscriptionsAdminClient.<SubscriptionsGet_Call>d__182.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.PowerShell.Cmdlets.SubscriptionsAdmin.SubscriptionsAdminClient.<SubscriptionsGet>d__180.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.PowerShell.Cmdlets.SubscriptionsAdmin.Cmdlets.GetAzsUserSubscription_Get.<ProcessRecordAsync>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.PowerShell.Cmdlets.SubscriptionsAdmin.Cmdlets.GetAzsUserSubscription_Get.<ProcessRecordAsync>d__59.MoveNext()'
DEBUG: CmdletException: ArgumentException - Argument passed in is not serializable.
Parameter name: value :    at System.Collections.ListDictionaryInternal.set_Item(Object key, Object value)
   at Microsoft.Azure.Commands.Common.AzModule.<OnFinally>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Commands.Common.AzModule.<EventListener>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.PowerShell.Cmdlets.SubscriptionsAdmin.Module.<Signal>d__48.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.PowerShell.Cmdlets.SubscriptionsAdmin.Cmdlets.GetAzsUserSubscription_Get.<Microsoft-Azure-PowerShell-Cmdlets-SubscriptionsAdmin-Runtime-IEventListe
ner-Signal>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.PowerShell.Cmdlets.SubscriptionsAdmin.SubscriptionsAdminClient.<SubscriptionsGet_Call>d__182.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.PowerShell.Cmdlets.SubscriptionsAdmin.SubscriptionsAdminClient.<SubscriptionsGet>d__180.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.PowerShell.Cmdlets.SubscriptionsAdmin.Cmdlets.GetAzsUserSubscription_Get.<ProcessRecordAsync>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.PowerShell.Cmdlets.SubscriptionsAdmin.Cmdlets.GetAzsUserSubscription_Get.<ProcessRecordAsync>d__59.MoveNext()
Get-AzsUserSubscription : Argument passed in is not serializable.
Parameter name: value
At line:1 char:1
+ Get-AzsUserSubscription -TargetSubscriptionId "966bbf24-21ce-43bd-873 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzsUserSubscription_Get], ArgumentException
    + FullyQualifiedErrorId : Microsoft.Azure.PowerShell.Cmdlets.SubscriptionsAdmin.Cmdlets.GetAzsUserSubscription_Get
 
DEBUG: CmdletProcessRecordEnd: 
DEBUG: [CmdletEndProcessing]: Sending new QosEvent for command 'Get-AzsUserSubscription_Get': AzureQoSEvent: CommandName - Get-AzsUserSubscription_Get; IsSuccess - True;
 Duration - 00:00:00
DEBUG: CmdletEndProcessing: 
```

**Comment by dolauli** [comment]
@rakku-ms Would you post how the error response is defined in swagger?

**Comment by rakku-ms** [comment]
@dolauli doesn't look like error response has been defined in swagger. Here is the swagger file: https://github.com/Azure/azure-rest-api-specs/blob/stackadmin2/specification/azsadmin/resource-manager/subscriptions/Microsoft.Subscriptions.Admin/preview/2015-11-01/Subscriptions.json
FYI @bganapa

**Comment by dolauli** [comment]
@rakku-ms An expected error response should be as https://github.com/Azure/azure-rest-api-specs/blob/stackadmin2/specification/databricks/resource-manager/Microsoft.Databricks/stable/2018-04-01/databricks.json#L73

**Comment by dolauli** [comment]
Should be an issue in swagger
