### ISSUE TITLE
`ParameterBindingException` is thrown when building modules from a directory with special characters in the name

### ISSUE THREAD

**Issue by peombwa** [Azure/autorest.powershell#845]
Customers are unable to import/build the generated PowerShell module when the `output-directory` contains special characters in its name.

### Repro Steps
1.  Clone this repo - `git clone https://github.com/Azure/autorest.powershell.git`.
2. Change directory to `autorest.powershell\samples\TimesWire` - `cd .\autorest.powershell\samples\TimesWire`.
3. Run `autorest --output-folder:"OneDrive - L’économie" .\readme.md` to generate a PowerShell module using the `TimesWire` sample with the `--output-folder` set to `"OneDrive - L’économie"`.
4. Run `. ".\OneDrive - L’économie\build-module.ps1"` to build the generated module.
5. The following exception is thrown:
``` powershell
Creating isolated process...
Cleaning build folders...
Compiling module...
Creating cmdlets for specified models...
Creating exports and docs...
$ParameterBindingException/   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
   at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
   at System.Management.Automation.ScriptBlock.DoInvokeReturnAsIs(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Object[] args)
   at System.Management.Automation.CommandInvocationIntrinsics.InvokeScript(ScriptBlock sb, Boolean useNewScope, PipelineResultTypes writeToPipeline, IList input, Object[] args)
   at System.Management.Automation.CommandInvocationIntrinsics.InvokeScript(String script, Boolean useNewScope, PipelineResultTypes writeToPipeline, IList input, Object[] args)
   at System.Management.Automation.CommandInvocationIntrinsics.InvokeScript(String script)
   at Times.Wire.Search.Runtime.PowerShell.PsHelpers.RunScript[T](CommandInvocationIntrinsics cii, String script) in F:\Azure\autorest.powershell\samples\TimesWire\OneDrive - L’économie\generated\runtime\BuildTime\PsHelpers.cs:line 24
   at Times.Wire.Search.Runtime.PowerShell.PsExtensions.RunScript[T](PSCmdlet cmdlet, String script) in F:\Azure\autorest.powershell\samples\TimesWire\OneDrive - L’économie\generated\runtime\BuildTime\PsExtensions.cs:line 137
   at Times.Wire.Search.Runtime.PowerShell.PsHelpers.GetModuleCmdletsAndHelpInfo(PSCmdlet cmdlet, String[] modulePaths) in F:\Azure\autorest.powershell\samples\TimesWire\OneDrive - L’économie\generated\runtime\BuildTime\PsHelpers.cs:line 72
   at Times.Wire.Search.Runtime.PowerShell.ExportProxyCmdlet.ProcessRecord() in F:\Azure\autorest.powershell\samples\TimesWire\OneDrive - L’économie\generated\runtime\BuildTime\Cmdlets\ExportProxyCmdlet.cs:line 59
Export-ProxyCmdlet: F:\Azure\autorest.powershell\samples\TimesWire\OneDrive - L’économie\build-module.ps1:132
Line |
 132 |    Export-ProxyCmdlet -ModuleName $moduleName -ModulePath $modulePaths …
     |    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | A positional parameter cannot be found that accepts argument 'économie\bin\TimesNewswire.private.dll -PassThru) | Where-Object { $_.CommandType -ne Alias } | ForEach-Object { @{ CommandInfo = $_; HelpInfo = ( invoke-command { try { Get-Help -Name $_.Name -Full } catch{ ' } } ) } }) + (Get-Command -Module (Import-Module
     | F:\Azure\autorest.powershell\samples\TimesWire\OneDrive'.
```

A similar exception is thrown when one imports the resulting module from a directory with special characters in its name, i.e., `Import-Module ".\OneDrive - L’économie\TimesNewswire.psd1"`. Related to https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/879

### Environment
``` powershell
AutoRest code generation utility [cli version: 3.3.2; node: v14.17.3]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
NOTE: AutoRest core version selected from configuration: 3.0.6306.

There is a new version of AutoRest available (3.4.0).
 > You can install the newer version with with npm install -g autorest@latest
   Loading AutoRest core      'C:\Users\peter\.autorest\@autorest_core@3.0.6306\node_modules\@autorest\core\dist' (3.0.6306)
   Loading AutoRest extension '@autorest/powershell' (~2.1.327->2.1.402)
   Loading AutoRest extension '@autorest/remodeler' (~2.1.0->2.1.27)
```
and 
``` powershell
AutoRest code generation utility [cli version: 3.3.2; node: v14.17.3]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest

There is a new version of AutoRest available (3.4.0).
 > You can install the newer version with with npm install -g autorest@latest
   Loading AutoRest core      'C:\Users\peter\.autorest\@autorest_core@3.0.6306\node_modules\@autorest\core\dist' (3.0.6306)
   Loading AutoRest extension '@autorest/powershell' (latest->3.0.455)
   Loading AutoRest extension '@autorest/modelerfour' (4.15.414->4.15.414)
```

**Comment by remygaronsanterre** [comment]
The fix is incomplete ; loading Microsoft.Graph.Authentication generates an error related to the special characters but deeper into the loading process.

Import-Module -Name Microsoft.Graph.Intune, Microsoft.Graph.Authentication

$ParseException/   à System.Management.Automation.ScriptBlock.Create(Parser parser, String fileName, String fileContents)
   à System.Management.Automation.ScriptBlock.Create(ExecutionContext context, String script)
   à System.Management.Automation.CommandInvocationIntrinsics.InvokeScript(String script, Boolean useNewScope, PipelineResultTypes writeToPipeline, IList input, Object[] args)
   à Microsoft.Graph.PowerShell.PSCmdletExtensions.RunScript[T](CommandInvocationIntrinsics cii, String script)
   à Microsoft.Graph.PowerShell.PSCmdletExtensions.RunScript[T](PSCmdlet cmdlet, String script)
   à Microsoft.Graph.PowerShell.Authentication.Utilities.Runtime.Cmdlets.GetScriptCmdlet.ProcessRecord()
Get-ScriptCmdlet : Au caractère Ligne:3 : 223
+ ... m' -Recurse -Include '*.ps1' -File | ForEach-Object { . $_.FullName }
+                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Le terminateur ' est manquant dans la chaîne.
Au caractère C:\Users\regarons\OneDrive\OneDrive - Ministère de l'économie\Documents\WindowsPowerShell\Modules\Microsoft.Graph.Authentication\1.9.3\StartupScripts\ExportCustomCommands.ps1:11 : 36
+ ... r -Function (Get-ScriptCmdlet -ScriptFolder $CustomScriptPath) -Alias ...
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ParserError: (:) [Get-ScriptCmdlet], ParseException
    + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString,Microsoft.Graph.PowerShell.Authentication.Utilities.Runtime.Cmdlets.GetScriptCmdlet

**Comment by dolauli** [comment]
Fixed in https://www.npmjs.com/package/@autorest/powershell/v/3.0.490
