### ISSUE TITLE
PLUGIN FAILURE: Cannot read property 'url' of undefined

### ISSUE THREAD

**Issue by eosfor** [Azure/autorest.powershell#86]
Hello colleagues, trying this against my endpoint

```
PS C:\temp\TRSModule> autorest --use:c:\Repo\Github\Public\MSFT\autorest.powershell --input-file:.\swagger.json
AutoRest code generation utility [version: 3.0.5160; node: v10.15.3]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\user\.autorest\@microsoft.azure_autorest-core@3.0.5378\node_modules\@microsoft.azure\autorest-core\dist' (3.0.5378)
   Loading local AutoRest extension 'autorest.powershell-testing' (c:\Repo\Github\Public\MSFT\autorest.powershell)
   Loading local AutoRest extension '@microsoft.azure/autorest.powershell' (c:/Repo/Github/Public/MSFT/autorest.powershell//extensions/powershell)
   Loading AutoRest extension '@microsoft.azure/autorest.remodeler' (beta->1.0.126)
   Loading AutoRest extension '@microsoft.azure/autorest.csharp-v2' (beta->1.0.137)
--------------------------------------------------------------------
C:\Repo\Github\Public\MSFT\autorest.powershell\extensions\csharp-v2\dist\plugin-llcsharp.js - {}
PLUGIN FAILURE: Cannot read property 'url' of undefined, TypeError: Cannot read property 'url' of undefined
    at new OperationMethod (C:\Repo\Github\Public\MSFT\autorest.powershell\extensions\csharp-v2\src\operation\method.ts:101:48)
    at new ApiClass (C:\Repo\Github\Public\MSFT\autorest.powershell\extensions\csharp-v2\src\operation\api-class.ts:30:31)
    at Project.init (C:\Repo\Github\Public\MSFT\autorest.powershell\extensions\csharp-v2\src\project.ts:68:5), {}
FATAL: TypeError: Cannot read property 'url' of undefined
C:\Users\user\.autorest\@microsoft.azure_autorest-core@3.0.5378\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\pipeline.js - FAILURE {}
(node:6024) UnhandledPromiseRejectionWarning: Error: Plugin llcsharp reported failure.
    at C:\Users\user\.autorest\@microsoft.azure_autorest-core@3.0.5378\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\external.js:26:19
(node:6024) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 31)
(node:6024) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:6024) UnhandledPromiseRejectionWarning: Error: Plugin llcsharp reported failure.
    at C:\Users\user\.autorest\@microsoft.azure_autorest-core@3.0.5378\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\external.js:26:19
(node:6024) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 32)
Process() cancelled due to exception : Plugin llcsharp reported failure. / Error: Plugin llcsharp reported failure.
    at C:\Users\user\.autorest\@microsoft.azure_autorest-core@3.0.5378\node_modules\@microsoft.azure\autorest-core\dist\lib\pipeline\plugins\external.js:26:19
```

what do i do to debug this in VS code (I'm new to node.js and all that "good stuff")

Thanks

**Comment by NelsonDaniel** [comment]
Hey @eosfor, try adding the flag --powershell-testing.debugger, and then in the debug tab from VSCode click on the arrow next to 'Attach'.

**Comment by VictorioBerra** [comment]
What was the fix?

**Comment by jeremy-collette** [comment]
I found that I had to add:
`  "basePath": "/",`
to my swagger spec to workaround this.

**Comment by jeremy-collette** [comment]
I also noticed that if i added a host, e.g.
`"host": "petstore.swagger.io",`
I also had to define a scheme, e.g.
```
  "schemes": [
    "http"
  ],
```
