### ISSUE TITLE
OperationId ending with _All throws: Error: Missing operation id?

### ISSUE THREAD

**Issue by ThePoShWolf** [Azure/autorest.powershell#879]
Here is the barebones json that will throw an error when generating with PowerShell:

```json
{
    "swagger": "2.0",
    "info": {
        "title": "Test API",
        "version": "2.0"
    },
    "host": "url.com",
    "produces": [
        "application/json"
    ],
    "paths": {
        "/api/path": {
            "get": {
                "operationId": "Anything_All",
                "responses": {
                    "200": {
                        "description": "",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}
```

And the command being run:

```
autorest --powershell --input-file:"C:\path\to\swaggertest.json" --debug
```

Here is the error debug output:

```
PLUGIN FAILURE: Missing operation id?, Error: Missing operation id?
    at Inferrer.inferCommand (C:\Path\to\.autorest\@autorest_powershell@3.0.467\node_modules\@autorest\powershell\plugins\create-commands-v2.ts:164:15)
    at Inferrer.inferCommandNames (C:\Path\to\.autorest\@autorest_powershell@3.0.467\node_modules\@autorest\powershell\plugins\create-commands-v2.ts:269:17)
    at Inferrer.createCommands (C:\Path\to\.autorest\@autorest_powershell@3.0.467\node_modules\@autorest\powershell\plugins\create-commands-v2.ts:145:42)
    at createCommandsV2 (C:\Path\to\.autorest\@autorest_powershell@3.0.467\node_modules\@autorest\powershell\plugins\create-commands-v2.ts:481:118)
    at C:\Path\to\.autorest\@autorest_powershell@3.0.467\node_modules\@azure-tools\autorest-extension-base\extension-base.ts:68:9, {}
fatal   | Error: Missing operation id?
C:\Path\to\.autorest\@autorest_core@3.7.2\node_modules\@autorest\core\dist\src_lib_autorest-core_ts.js - FAILURE Error: Plugin create-commands-v2 reported failure.
    at C:\Path\to\.autorest\@autorest_core@3.7.2\node_modules\@autorest\core\dist\src_lib_autorest-core_ts.js:2779:19
    at ScheduleNode (C:\Path\to\.autorest\@autorest_core@3.7.2\node_modules\@autorest\core\dist\src_lib_autorest-core_ts.js:1317:33)
fatal   | Process() cancelled due to exception : Plugin create-commands-v2 reported failure. / Error: Plugin create-commands-v2 reported failure.
    at C:\Path\to\.autorest\@autorestcore@3.7.2\node_modules\@autorest\core\dist\src_lib_autorest-corets.js:2779:19
    at ScheduleNode (C:\Path\to\.autorest\@autorestcore@3.7.2\node_modules\@autorest\core\dist\src_lib_autorest-corets.js:1317:33)
error   |   Error: Plugin create-commands-v2 reported failure.
```

The full swagger doc does produce a python module using autorest.

In testing various possibilities, I discovered that when changing the `operationId` to anything that ends with _All, it will throw the above error.

Output of `autorest --version`:

```
SourceMapConsumer.initialize is a no-op when running in node.js
AutoRest code generation utility [cli version: 3.5.1; node: v12.19.0]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest


Showing All Installed Extensions

 Type       Extension Name                           Version      Location
 core       @autorest/core                           3.7.2        C:\path\to\.autorest\@autorest_core@3.7.2
 extension  @autorest/modelerfour                    4.15.414     C:\path\to\.autorest\@autorest_modelerfour@4.15.414
 extension  @autorest/modelerfour                    4.19.3       C:\path\to\.autorest\@autorest_modelerfour@4.19.3
 extension  @autorest/powershell                     3.0.467      C:\path\to\.autorest\@autorest_powershell@3.0.467
 extension  @autorest/python                         5.12.0       C:\path\to\.autorest\@autorest_python@5.12.0
```

**Comment by dolauli** [comment]
To prevent using **all** the operation is actually by design. See following code for details. To use xxx_all as an operation Id does not make sense. Generally speaking, the operation should be something like {noun}_{verb}

https://github.com/Azure/autorest.powershell/blob/a638a03496b72ea7053a3b09c60cab77b226aed2/powershell/plugins/create-commands-v2.ts#L181

**Comment by ThePoShWolf** [comment]
I'm not sure if any changes were made and I'm not currently supporting an AutoRest module to be able to test, but I would suggest a better error message to make this easier the next time someone comes across it. This is a really easy fix and, if I remember correctly, was happenstance that I found the solution.
