### ISSUE TITLE
Cryptic Error Message when generating module

### ISSUE THREAD

**Issue by georgend** [Azure/autorest.powershell#904]
When generating a module we are getting the error message

```
PLUGIN FAILURE: Cannot read property 'enum' of undefined, TypeError: Cannot read property 'enum' of undefined
```

Any clues or pointers regarding the cause of the error?

Full Log Attached [here](https://gist.github.com/georgend/e5f2f845f5693b9bf7f491475ac65e53)

**Comment by dolauli** [comment]
@georgend  Would you share with me the swagger that leads to the issue?

**Comment by georgend** [comment]
https://gist.github.com/georgend/42b1965a894aa3a0045a1d7757b32b35

https://gist.github.com/georgend/3c30019143f3f70babd403a1c889ab00

Those are the two files.

**Comment by dolauli** [comment]
@georgend  The error I run into is in autorest/core, which is different from yours. Would you confirm whether we are using the same swaggers or do I miss anything?
```
PS C:\Users\xidi\source\azure-powershell\src\Databricks> autorest --use:@autorest/powershell@2.1.401 --debug
SourceMapConsumer.initialize is a no-op when running in node.js
AutoRest code generation utility [cli version: 3.5.1; node: v14.15.5]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
debug   | [1.09 s] Network Enabled: true
debug   | [1.17 s] The most recent installed version is 3.7.6
debug   | [1.17 s] requesting current version '3.7.6'
debug   | [1.17 s] Starting @autorest/core from C:\Users\xidi\.autorest\@autorestcore@3.7.6\nodemodules\@autorest\core
SourceMapConsumer.initialize is a no-op when running in node.js
info    |    Loading AutoRest core      'C:\Users\xidi\.autorest\@autorestcore@3.7.6\nodemodules\@autorest\core\dist' (3.7.6)
verbose | [0.96 s]    Initial configuration file 'file:///C:/Users/xidi/source/azure-powershell/src/Databricks/README.md'
verbose | [0.96 s]    Including configuration file 'file:///C:/Users/xidi/source/azure-powershell/src/Databricks/README.md'
verbose | [0.99 s]    Including configuration file 'file:///C:/Users/xidi/source/azure-powershell/src/readme.azure.noprofile.md'
verbose | [1.00 s]    Including configuration file 'file:///C:/Users/xidi/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist/resources/default-configuration.md'
verbose | [1.02 s]    Including configuration file 'file:///C:/Users/xidi/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist/resources/inspect.md'
verbose | [1.04 s]    Including configuration file 'file:///C:/Users/xidi/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist/resources/directives.md'
verbose | [1.08 s]    Including configuration file 'file:///C:/Users/xidi/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist/resources/pipeline.md'
verbose | [1.11 s]    Including configuration file 'file:///C:/Users/xidi/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist/resources/loader-openapi.md'
verbose | [1.14 s]    Including configuration file 'file:///C:/Users/xidi/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist/resources/miscellaneous.md'
verbose | [1.15 s]    Including configuration file 'file:///C:/Users/xidi/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist/resources/plugin-powershell.md'
verbose | [1.17 s]    Including configuration file 'file:///C:/Users/xidi/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist/resources/plugin-azureresourceschema.md'
verbose | [1.18 s]    Including configuration file 'file:///C:/Users/xidi/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist/resources/plugin-csharp.md'
verbose | [1.20 s]    Including configuration file 'file:///C:/Users/xidi/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist/resources/plugin-go.md'
verbose | [1.21 s]    Including configuration file 'file:///C:/Users/xidi/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist/resources/plugin-java.md'
verbose | [1.27 s]    Including configuration file 'file:///C:/Users/xidi/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist/resources/plugin-nodejs.md'
verbose | [1.29 s]    Including configuration file 'file:///C:/Users/xidi/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist/resources/plugin-php.md'
verbose | [1.31 s]    Including configuration file 'file:///C:/Users/xidi/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist/resources/plugin-python.md'
verbose | [1.34 s]    Including configuration file 'file:///C:/Users/xidi/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist/resources/plugin-ruby.md'
verbose | [1.37 s]    Including configuration file 'file:///C:/Users/xidi/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist/resources/plugin-typescript.md'
verbose | [1.40 s]    Including configuration file 'file:///C:/Users/xidi/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist/resources/plugin-validators.md'
verbose | [1.42 s]    Including configuration file 'file:///C:/Users/xidi/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist/resources/plugin-az.md'
verbose | [1.45 s]    Including configuration file 'file:///C:/Users/xidi/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist/resources/plugin-terraform.md'
verbose | [1.47 s]    Including configuration file 'file:///C:/Users/xidi/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist/resources/plugin-azure-functions.md'
verbose | [1.50 s]    Including configuration file 'file:///C:/Users/xidi/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist/resources/graphs.md'
verbose | [1.52 s]    Including configuration file 'file:///C:/Users/xidi/.autorest/@autorestcore@3.7.6/nodemodules/@autorest/core/dist/resources/help-configuration.md'
info    | 
The default version of @autorest/powershell has been bumped from 2.1+ to 3.0+.
 > If you still want to use 2.1+ version, please specify it with --use:@autorest/powershell@2.1.{x}, e.g 2.1.401.

info    |    Loading AutoRest extension '@autorest/powershell' (2.1.401->2.1.401)
verbose | [1.65 s]    Including extension configuration file 'file:///C:/Users/xidi/.autorest/@autorestpowershell@2.1.401/nodemodules/@autorest/powershell/readme.md'
verbose | [1.65 s]    Including configuration file 'file:///C:/Users/xidi/.autorest/@autorestpowershell@2.1.401/nodemodules/@autorest/powershell/readme.md'
verbose | [1.68 s]    Including configuration file 'file:///C:/Users/xidi/.autorest/@autorestpowershell@2.1.401/nodemodules/@autorest/powershell/autorest-configuration.md'
info    |    Loading AutoRest extension '@autorest/remodeler' (~2.1.0->2.1.27)
verbose | [1.84 s]    Including extension configuration file 'file:///C:/Users/xidi/.autorest/@autorestremodeler@2.1.27/nodemodules/@autorest/remodeler/readme.md'
verbose | [1.84 s]    Including configuration file 'file:///C:/Users/xidi/.autorest/@autorestremodeler@2.1.27/nodemodules/@autorest/remodeler/readme.md'
debug   | [2.88 s] swagger-document/loader-swagger - START inputs = 0
debug   | [2.88 s] openapi-document/loader-openapi - START inputs = 0
debug   | [2.88 s] pipeline-emitter - START inputs = 0
debug   | [2.88 s] configuration-emitter - START inputs = 0
debug   | [2.88 s] pipeline-emitter - END [0.05 s][77 MB]
debug   | [2.88 s] configuration-emitter - END [0.05 s][77 MB]
verbose | [3.09 s] Reading OpenAPI 3.0 file https://gist.github.com/georgend/42b1965a894aa3a0045a1d7757b32b35
verbose | [3.43 s] Reading OpenAPI 3.0 file https://gist.github.com/georgend/3c30019143f3f70babd403a1c889ab00
debug   | [3.44 s] swagger-document/loader-swagger - END [0.6 s][81 MB]
debug   | [3.53 s] openapi-document/loader-openapi - END [0.7 s][83 MB]
debug   | [3.53 s] swagger-document/individual/transform - SKIPPING
debug   | [3.53 s] swagger-document/individual/schema-validator-swagger - SKIPPING
debug   | [3.53 s] swagger-document/identity - SKIPPING
debug   | [3.53 s] swagger-document/individual/identity - SKIPPING
debug   | [3.53 s] openapi-document/openapi-document-converter - SKIPPING
debug   | [3.53 s] openapi-document/individual/transform - START inputs = 2
debug   | [3.55 s] openapi-document/individual/transform - END [0.01 s][85 MB]
debug   | [3.55 s] openapi-document/individual/schema-validator-openapi - START inputs = 2
debug   | [3.73 s] openapi-document/individual/schema-validator-openapi - END [0.18 s][87 MB]
debug   | [3.73 s] openapi-document/individual/identity - START inputs = 2
debug   | [3.73 s] openapi-document/individual/identity - END [0 s][87 MB]
debug   | [3.74 s] openapi-document/transform - START inputs = 2
debug   | [3.74 s] openapi-document/transform - END [0 s][87 MB]
debug   | [3.74 s] openapi-document/semantic-validator - START inputs = 2
debug   | [3.74 s] openapi-document/semantic-validator - END [0 s][89 MB]
debug   | [3.75 s] openapi-document/allof-cleaner - START inputs = 2
debug   | [3.76 s] openapi-document/allof-cleaner - END [0.01 s][91 MB]
debug   | [3.76 s] openapi-document/tree-shaker - START inputs = 2
debug   | [3.88 s] openapi-document/tree-shaker - END [0.11 s][98 MB]
debug   | [3.88 s] openapi-document/multi-api-merger - START inputs = 2
debug   | [3.98 s] openapi-document/multi-api-merger - END [0.1 s][97 MB]
debug   | [3.98 s] openapi-document/components-cleaner - START inputs = 1
debug   | [4.05 s] openapi-document/components-cleaner - END [0.07 s][106 MB]
debug   | [4.05 s] openapi-document/component-modifiers - START inputs = 1
debug   | [4.06 s] openapi-document/component-modifiers - END [0 s][112 MB]
debug   | [4.07 s] openapi-document/api-version-parameter-handler - START inputs = 1
debug   | [4.07 s] openapi-document/api-version-parameter-handler - END [0 s][101 MB]
debug   | [4.07 s] openapi-document/profile-filter - START inputs = 1
debug   | [4.07 s] openapi-document/profile-filter - END [0 s][101 MB]
debug   | [4.07 s] openapi-document/model-deduplicator - START inputs = 1
debug   | [4.08 s] openapi-document/emitter - START inputs = 1
debug   | [4.08 s] openapi-document/emitter - END [0 s][101 MB]
C:\Users\xidi\.autorest\@autorest_core@3.7.6\node_modules\@autorest\core\dist\src_lib_autorest-core_ts.js - FAILURE TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at getMergedProfilesMetadata (C:\Users\xidi\.autorest\@autorest_core@3.7.6\node_modules\@autorest\core\dist\src_lib_autorest-core_ts.js:16349:39)
    at Deduplicator.deduplicatePaths (C:\Users\xidi\.autorest\@autorest_core@3.7.6\node_modules\@autorest\core\dist\src_lib_autorest-core_ts.js:16505:40)
    at Deduplicator.init (C:\Users\xidi\.autorest\@autorest_core@3.7.6\node_modules\@autorest\core\dist\src_lib_autorest-core_ts.js:16428:26)
    at Deduplicator.getOutput (C:\Users\xidi\.autorest\@autorest_core@3.7.6\node_modules\@autorest\core\dist\src_lib_autorest-core_ts.js:16697:13)
    at deduplicate (C:\Users\xidi\.autorest\@autorest_core@3.7.6\node_modules\@autorest\core\dist\src_lib_autorest-core_ts.js:2430:76)
    at ScheduleNode (C:\Users\xidi\.autorest\@autorest_core@3.7.6\node_modules\@autorest\core\dist\src_lib_autorest-core_ts.js:1317:33)
fatal   | Process() cancelled due to exception : Cannot convert undefined or null to object / TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at getMergedProfilesMetadata (C:\Users\xidi\.autorest\@autorestcore@3.7.6\node_modules\@autorest\core\dist\src_lib_autorest-corets.js:16349:39)
    at Deduplicator.deduplicatePaths (C:\Users\xidi\.autorest\@autorestcore@3.7.6\node_modules\@autorest\core\dist\src_lib_autorest-corets.js:16505:40)
    at Deduplicator.init (C:\Users\xidi\.autorest\@autorestcore@3.7.6\node_modules\@autorest\core\dist\src_lib_autorest-corets.js:16428:26)
    at Deduplicator.getOutput (C:\Users\xidi\.autorest\@autorestcore@3.7.6\node_modules\@autorest\core\dist\src_lib_autorest-corets.js:16697:13)
    at deduplicate (C:\Users\xidi\.autorest\@autorestcore@3.7.6\node_modules\@autorest\core\dist\src_lib_autorest-corets.js:2430:76)
    at ScheduleNode (C:\Users\xidi\.autorest\@autorestcore@3.7.6\node_modules\@autorest\core\dist\src_lib_autorest-corets.js:1317:33)
error   |   TypeError: Cannot convert undefined or null to object
debug   | [4.97 s] Shutting Down.
debug   | [4.98 s] Exiting.
```

**Comment by georgend** [comment]
I cannot clearly tell from my error log whether the issue is in AutoRest Core or AutoRest Powershell. 

The general behavior (which you have reproduced) is that with that particular openapi document, we get an error. 

I want to identify what's wrong with the OpenAPI document but I can't since I don't understand the error message from autorest infrastructure.

**Comment by dolauli** [comment]
> I cannot clearly tell from my error log whether the issue is in AutoRest Core or AutoRest Powershell.
> 
> The general behavior (which you have reproduced) is that with that particular openapi document, we get an error.
> 
> I want to identify what's wrong with the OpenAPI document but I can't since I don't understand the error message from autorest infrastructure.

@georgend From your log, I could see it is an autorest powershell issue, since the plugin tweakcodemodel is in autorest powershell. But from my log, it is another error that is reported in autorest core. Before I could provide support for your issue, I need to reproduce it in my side.

**Comment by peombwa** [comment]
@dolauli, @georgend is using @autorest/powershell@2.1.700 ([msgraph branch](https://github.com/Azure/autorest.powershell/tree/msgraph/powershell)) and not @autorest/powershell@2.1.401 that you are using.

**Comment by dolauli** [comment]
@peombwa, I try to use the autorest.powershell, which I built from msgraph branch. I still could not reproduce the issue mentioned by @georgend. And in my side, it reported another issue in autorest/core. For autorest/core issue, I will need to move it to autorest repo, which is owned by autorest team.

**Comment by georgend** [comment]
@dolauli Yes we can move it to probably see if we can get a resolution.
