### ISSUE TITLE
Add Support for Parameter Objects with Content Property

### ISSUE THREAD

**Issue by peombwa** [Azure/autorest.powershell#919]
AutoREST.PowerShell fails with `error   |   Error: Plugin modelerfour reported failure` when the parameter object of an operation contains `content` property:
![image](https://user-images.githubusercontent.com/7061532/158900501-61bbbd3d-6743-4792-ae82-d191554901c5.png)

### Repro Steps
1. Use an OpenAPI description where the parameter object of an operation is defined as `content`. e.g., [DeviceManagement.Functions.yml](https://gist.github.com/peombwa/8be839787ab6356d30366229f9fd9dc3).
2. Run AutoREST to generate a module using the above OpenAPI file:
    ``` powershell
        $OpenApiFile = "https://gist.githubusercontent.com/peombwa/8be839787ab6356d30366229f9fd9dc3/raw/bd442972339ea00b523ccb5c79c2e87ef5dd8aab/DeviceManagement.Functions.yml"
        autorest --powershell --input-file:$OpenApiFile --debug
    ```
3. AutoREST fails with:
    ``` powershell
        AutoRest code generation utility [cli version: 3.6.0; node: v14.11.0]
        info    |    Loading AutoRest extension '@autorest/powershell' (~3.0.0->3.0.471)
        info    |    Loading AutoRest extension '@autorest/modelerfour' (4.15.414->4.15.414)
        ...
        C:\Users\peter\.autorest\@autorest_modelerfour@4.15.414\node_modules\@autorest\modelerfour\dist\modeler\plugin-modelerfour.js - FAILURE  "Unresolved item." undefined
        PLUGIN FAILURE: undefined, undefined, "Unresolved item."
        fatal   | Unresolved item.
        C:\Users\peter\.autorest\@autorest_core@3.7.4\node_modules\@autorest\core\dist\src_lib_autorest-core_ts.js - FAILURE Error: Plugin modelerfour reported failure.
            at C:\Users\peter\.autorest\@autorest_core@3.7.4\node_modules\@autorest\core\dist\src_lib_autorest-core_ts.js:2779:19
            at ScheduleNode (C:\Users\peter\.autorest\@autorest_core@3.7.4\node_modules\@autorest\core\dist\src_lib_autorest-core_ts.js:1317:33)
        fatal   | Process() cancelled due to exception : Plugin modelerfour reported failure. / Error: Plugin modelerfour reported failure.
            at C:\Users\peter\.autorest\@autorestcore@3.7.4\node_modules\@autorest\core\dist\src_lib_autorest-corets.js:2779:19
            at ScheduleNode (C:\Users\peter\.autorest\@autorestcore@3.7.4\node_modules\@autorest\core\dist\src_lib_autorest-corets.js:1317:33)
        error   |   Error: Plugin modelerfour reported failure.
        debug   | [2.56 s] Shutting Down.
        debug   | [2.56 s] Exiting.
    ```

### Expected behavior
AutoREST.PowerShell should generate a command for `/deviceManagement/microsoft.graph.getRoleScopeTagsByIds(ids={ids})` that makes `GET /deviceManagement/microsoft.graph.getRoleScopeTagsByIds(ids=["1","2","3"])` request.

According to the [OpenAPI spec](https://spec.openapis.org/oas/v3.1.0#parameter-object):
> For more complex scenarios, the [content](https://spec.openapis.org/oas/v3.1.0#parameterContent) property can define the media type and schema of the parameter. A parameter MUST contain either a schema property, or a content property, but not both.

**Comment by dolauli** [comment]
It is a modelerfour issue. Transfer it to autorest.
