### ISSUE TITLE
The parameter 'Body' has multiple parameter types [IEntityRegionInfo, IUpdateRegion] defined, which is not supported.

### ISSUE THREAD

**Issue by JnaneshD05** [Azure/autorest.powershell#941]
Compiling the generated using .\buil-module.ps1 gives error like this.  Command used : autorest .\Configuration.yaml --namespace="Commvault.Powershell" --output-folder="C:\cvpowers\SP28" --powershell  --input-file=OpenAPI3_modified.yaml --verbose -
[OpenAPI3_modified.txt](https://github.com/Azure/autorest.powershell/files/8705702/OpenAPI3_modified.txt)
-clear-output-folder --use:@autorest/powershell@3.0.415

Creating exports and docs...
$ParsingMetadataException/   at Commvault.Powershell.Runtime.PowerShell.ParameterGroup..ctor(String parameterName, Parameter[] parameters, String[] allVariantNames) in C:\cvpowers\SP28\generated\runtime\BuildTime\Models\PsProxyTypes.cs:line 201
   at Commvault.Powershell.Runtime.PowerShell.PsProxyTypeExtensions.<>c__DisplayClass7_0.<ToParameterGroups>b__3(IGrouping`2 pg) in C:\cvpowers\SP28\generated\runtime\BuildTime\Models\PsProxyTypes.cs:line 487
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.ToArray()
   at Commvault.Powershell.Runtime.PowerShell.VariantGroup..ctor(String moduleName, String cmdletName, Variant[] variants, String outputFolder, String profileName, Boolean isTest, Boolean isInternal) in C:\cvpowers\SP28\generated\runtime\BuildTime\Models\PsProxyTypes.cs:line 66
   at Commvault.Powershell.Runtime.PowerShell.ExportProxyCmdlet.<>c__DisplayClass36_2.<ProcessRecord>b__10(IGrouping`2 vg) in C:\cvpowers\SP28\generated\runtime\BuildTime\Cmdlets\ExportProxyCmdlet.cs:line 68
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.SparseArrayBuilder`1.ReserveOrAdd(IEnumerable`1 items)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray()
   at Commvault.Powershell.Runtime.PowerShell.ExportProxyCmdlet.ProcessRecord() in C:\cvpowers\SP28\generated\runtime\BuildTime\Cmdlets\ExportProxyCmdlet.cs:line 66
Export-ProxyCmdlet: C:\cvpowers\SP28\build-module.ps1:134:3
Line |
 134 |    Export-ProxyCmdlet -ModuleName $moduleName -ModulePath $modulePaths …
     |    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The parameter 'Body' has multiple parameter types [IEntityRegionInfo, IUpdateRegion] defined, which is not supported.

Adding yaml file in txt format. Please help this

**Comment by dolauli** [comment]
You may rename the operationId **setRegionForEntity** to **setEntityRegion** to generate another cmdlet instead of be merging with the operation **UpdateRegion**.
